Repository OCA/OpenUpgrade, pull requests merged in 2018-06, with the labels that each got.

#1179 [11.0][MIG] Migration Script for purchase
  addons/purchase/migrations/11.0.1.2/noupdate_changes.xml
  addons/purchase/migrations/11.0.1.2/openupgrade_analysis_work.txt
  addons/purchase/migrations/11.0.1.2/post-migration.py
  addons/purchase/migrations/11.0.1.2/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: Blocked by dependency

#1103 [11.0][MIG] delivery
  addons/delivery/migrations/11.0.1.0/openupgrade_analysis_work.txt
  addons/delivery/migrations/11.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: approved

#1196 [11.0][MIG] sale_stock migration
  addons/sale/migrations/11.0.1.1/pre-migration.py
  addons/sale_stock/migrations/11.0.1.0/openupgrade_analysis_work.txt
  addons/sale_stock/migrations/11.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: Blocked by dependency

#1401 [ADD] portal_sale: Merged in sale + migration scripts
  addons/account/migrations/11.0.1.1/pre-migration.py
  addons/sale/migrations/11.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1402 [ADD] stock_account: Migration scripts
  addons/stock_account/migrations/11.0.1.1/openupgrade_analysis_work.txt
  addons/stock_account/migrations/11.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1076 [10.0][MIG] mrp
  addons/mrp/__manifest__.py
  addons/mrp/migrations/10.0.2.0/noupdate_changes.xml
  addons/mrp/migrations/10.0.2.0/openupgrade_analysis_work.txt
  addons/mrp/migrations/10.0.2.0/post-migration.py
  addons/mrp/migrations/10.0.2.0/pre-migration.py
  addons/resource/migrations/10.0.1.1/openupgrade_analysis_work.txt
  addons/resource/migrations/10.0.1.1/post-migration.py
  odoo/addons/base/migrations/10.0.1.3/pre-migration.py
  odoo/openupgrade/doc/source/modules90-100.rst
Labels: help wanted, needs review
