Repository OCA/OpenUpgrade, pull requests merged in 2019-07, with the labels that each got.

#1873 [11.0][MIG] account_check_printing
  addons/account_check_printing/migrations/11.0.1.0/noupdate_changes.xml
  addons/account_check_printing/migrations/11.0.1.0/openupgrade_analysis_work.txt
  addons/account_check_printing/migrations/11.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1680 [12.0][MIG] account_payment
  addons/account_payment/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1855 [12.0][MIG] pos_sale
  addons/pos_sale/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1906 [12.0][IMP] openupgrade_records: defaults and many2manys tables
  odoo/addons/openupgrade_records/lib/compare.py
  odoo/addons/openupgrade_records/models/openupgrade_record.py
  odoo/openupgrade/openupgrade_loading.py
Labels: approved, enhancement

#1779 [12.0][FIX] base: don't create user_admin if already exists
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#1917 [ADD] website_slides: Migration scripts
  addons/website_slides/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_slides/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_slides/migrations/12.0.1.0/post-migration.py
  addons/website_slides/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1920 [12.0][FIX] stock: merge stock_putaway_product
  addons/stock/migrations/12.0.1.1/post-migration.py
  addons/stock/migrations/12.0.1.1/pre-migration.py
Labels: needs review

#1924 [12.0][FIX] stock: push_pull rules broccoly
  addons/stock/migrations/12.0.1.1/post-migration.py
Labels: needs review

#1921 [ADD] website_event_track: Migration
  addons/website_event_track/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_event_track/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_event_track/migrations/12.0.1.0/post-migration.py
  addons/website_event_track/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1918 [12.0][FIX] hr_holidays: don't create wrong followers
  addons/hr_holidays/migrations/12.0.1.5/post-migration.py
Labels: approved, needs review

#1922 [ADD] website_mass_mailing: Migrate
  addons/mass_mailing/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/12.0.2.0/pre-migration.py
  addons/website_mass_mailing/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1915 [12.0][IMP] mail: fast fill add_sign in mail.message
  addons/mail/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/mail/migrations/12.0.1.0/pre-migration.py
Labels: needs review

#1916 [12.0][IMP] base: fast fill res_model_name in ir.attachment
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis_work.txt
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#1911 [12.0][IMP] openupgrade_records: avoid repeated words in analysis
  odoo/addons/openupgrade_records/lib/compare.py
Labels: needs review

#1940 [12.0][MIG] hr_payroll
  addons/hr_payroll/migrations/12.0.1.0/noupdate_changes.xml
  addons/hr_payroll/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/hr_payroll/migrations/12.0.1.0/post-migration.py
  addons/hr_payroll_account/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1935 [12.0][FIX] sale: avoid the automatic compute of qty_delivered_method
  addons/sale/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/sale/migrations/12.0.1.1/pre-migration.py
Labels: needs review

#1937 [12.0][MIG] sale_margin
  addons/sale_margin/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1942 [12.0][DOC] delivery
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1934 [12.0][IMP] mail: faster end-migration
  addons/mail/migrations/12.0.1.0/end-migration.py
Labels: needs review

#1936 [12.0][MIG] mrp_* (mrp related modules)
  addons/mrp_byproduct/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: Blocked by dependency, needs review

#1938 [12.0][MIG] purchase_requisition
  addons/purchase_requisition/migrations/12.0.0.1/noupdate_changes.xml
  addons/purchase_requisition/migrations/12.0.0.1/openupgrade_analysis_work.txt
  addons/purchase_requisition/migrations/12.0.0.1/post-migration.py
  addons/purchase_requisition/migrations/12.0.0.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1945 [11.0][MIG] web_widget_datepicker_options -> web
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1944 [FIX] website_seo_redirection: Relocate pages
  addons/website/migrations/11.0.1.0/post-migration.py
Labels: approved

#1933 [FIX] website: Fix menu & page structure migration
  addons/website/migrations/12.0.1.0/post-migration.py
  addons/website/migrations/12.0.1.0/pre-migration.py
  addons/website/models/ir_ui_view.py
Labels: needs review, question

#1950 [12.0][FIX] website_livechat: convert bootstrap
  addons/website_livechat/migrations/12.0.1.0/post-migration.py
Labels: needs review

#1683 [12.0][MIG] mrp
  addons/mrp/migrations/12.0.2.0/noupdate_changes.xml
  addons/mrp/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/mrp/migrations/12.0.2.0/post-migration.py
  addons/mrp/migrations/12.0.2.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1956 [12.0][FIX] mail_bot: set auto_install to false.
  addons/mail_bot/__manifest__.py
Labels: approved
