Repository OCA/OpenUpgrade, pull requests merged in 2019-02, with the labels that each got.

#1710 [12.0][UPD] openupgrade_records analysis
  addons/account/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/event_sale/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/hr_expense/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/hr_holidays/migrations/12.0.1.5/openupgrade_analysis.txt
  addons/l10n_be_invoice_bba/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/l10n_ch/migrations/12.0.10.0/openupgrade_analysis.txt
  addons/l10n_jp/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/l10n_lu/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/maintenance/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/mrp/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/product/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/purchase_requisition/migrations/12.0.0.1/openupgrade_analysis.txt
  addons/repair/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/sale_purchase/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_quotation_builder/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/stock/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/stock_dropshipping/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/stock_landed_costs/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/web/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/web_tour/migrations/12.0.0.1/openupgrade_analysis.txt
  addons/web_unsplash/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/website/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_forum/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_sale/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_general_log.txt
Labels: needs review

#1519 [FIX+IMP] sale_timesheet: Map track_service to service_tracking + use openupgradelib method
  addons/sale/migrations/11.0.1.1/pre-migration.py
  addons/sale_timesheet/migrations/11.0.1.0/post-migration.py
  addons/sale_timesheet/migrations/11.0.1.0/pre-migration.py
Labels: approved

#1702 [IMP] stock: Fill missing lots for stock.move.line
  addons/stock/migrations/11.0.1.1/post-migration.py
Labels: needs fixing

#1718 [FIX] UOM categories are called product.uom.categ in v11
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#1721 [11.0][IMP] website_event: add pre-migration
  addons/website_event/migrations/11.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1732 [12.0][MIG] note
  addons/note/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/note_pad/migrations/12.0.0.1/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1728 [12.0][MIG] base_automation
  addons/base_automation/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1744 [12.0][FIX] openupgrade_records: several fixes
  odoo/addons/openupgrade_records/lib/compare.py
  odoo/addons/openupgrade_records/models/analysis_wizard.py
  odoo/addons/openupgrade_records/models/openupgrade_record.py
  odoo/openupgrade/openupgrade_loading.py
Labels: enhancement, needs review

#1745 [12.0][UPD] new openupgrade analysis
  addons/account/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/account_payment/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/account_voucher/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/analytic/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/crm/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/delivery/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/fleet/migrations/12.0.0.1/openupgrade_analysis.txt
  addons/hr/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/hr_attendance/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/hr_expense/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/hr_holidays/migrations/12.0.1.5/openupgrade_analysis.txt
  addons/hr_recruitment/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/hr_timesheet/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_be_hr_payroll/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_be_hr_payroll_fleet/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_ch/migrations/12.0.10.0/openupgrade_analysis.txt
  addons/mail/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/maintenance/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/mass_mailing/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/mrp/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/note/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/partner_autocomplete/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/point_of_sale/migrations/12.0.1.0.1/openupgrade_analysis.txt
  addons/pos_sale/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/product/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/project/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/project_timesheet_holidays/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/purchase/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/purchase_stock/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/rating/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/repair/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/resource/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/sale/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/sale_management/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_purchase/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_quotation_builder/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_timesheet/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/stock/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/survey/migrations/12.0.3.0/openupgrade_analysis.txt
  addons/uom/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_blog/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_crm_partner_assign/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_customer/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_event/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_event_track/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_hr/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_hr_recruitment/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_livechat/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_partner/migrations/12.0.0.1/openupgrade_analysis.txt
  addons/website_sale/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_sale_delivery/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_sale_stock/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_slides/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_general_log.txt
Labels: needs review

#1746 [11.0][IMP] openupgrade_records: add compatibility (partial backport)
  odoo/addons/openupgrade_records/models/openupgrade_record.py
  odoo/openupgrade/openupgrade_loading.py
Labels: needs review

#1674 [12.0][MIG] project & pad_project
  addons/pad_project/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/project/migrations/12.0.1.1/noupdate_changes.xml
  addons/project/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/project/migrations/12.0.1.1/post-migration.py
  addons/project/migrations/12.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1729 [12.0][MIG] base_geolocalize
  addons/base_geolocalize/migrations/12.0.2.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1747 [ADD] migrate expense's attachments and messages
  addons/hr_expense/migrations/9.0.2.0/post-migration.py
Labels: needs review

#1738 [12.0][MIG] hr_contract
  addons/hr/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/hr/migrations/12.0.1.1/pre-migration.py
  addons/hr_contract/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/hr_contract/migrations/12.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1750 [12.0][UPD] updated docs of already migrated modules
  addons/analytic/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/analytic/migrations/12.0.1.1/post-migration.py
  addons/crm/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/hr/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/hr/migrations/12.0.1.1/post-migration.py
  addons/hr_attendance/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/product/migrations/12.0.1.2/openupgrade_analysis_work.txt
  addons/resource/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/uom/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/uom/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis_work.txt
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1677 [12.0][MIG] account
  addons/account/migrations/12.0.1.1/noupdate_changes.xml
  addons/account/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/12.0.1.1/post-migration.py
  addons/account/migrations/12.0.1.1/pre-migration.py
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review
