Repository OCA/OpenUpgrade, pull requests merged in 2019-09, with the labels that each got.

#1999 TEST
  odoo/addons/openupgrade_records/README.rst
Labels: work in progress

#1989 [11.0][FIX] project.issue : add the issues unrelated to projects
  addons/project/migrations/11.0.1.1/post-migration.py
Labels: approved, ready to merge

#1990 [12.0][MIG] mass_mailing_event: Nothing to do
  addons/mass_mailing_event/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1951 [12.0][MIG] website_quote / sale_quotation_builder
  addons/sale/migrations/12.0.1.1/post-migration.py
  addons/sale/migrations/12.0.1.1/pre-migration.py
  addons/sale_management/migrations/12.0.1.0/pre-migration.py
  addons/sale_quotation_builder/migrations/12.0.1.0/noupdate_changes.xml
  addons/sale_quotation_builder/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/sale_quotation_builder/migrations/12.0.1.0/post-migration.py
  addons/sale_quotation_builder/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#2012 [12.0][UPD] openupgrade_records: add model_type for model records
  odoo/addons/openupgrade_records/lib/compare.py
  odoo/addons/openupgrade_records/models/analysis_wizard.py
  odoo/addons/openupgrade_records/models/openupgrade_record.py
Labels: needs review

#2013 [11.0][UPD] openupgrade_records: complement (model_type)
  odoo/addons/openupgrade_records/models/openupgrade_record.py
Labels: needs review

#2021 [FIX] base: Preserve system user email
  odoo/addons/base/migrations/12.0.1.3/end-migration.py
Labels: approved

#2032 [12.0][IMP] openupgrade_records: consider merged models
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/addons/openupgrade_records/lib/compare.py
Labels: approved, needs review

#2038 [9.0][FIX] hr_recruitment: Model hr.applicant_category has been renamed
  addons/hr_recruitment/migrations/9.0.1.0/openupgrade_analysis_work.txt
  addons/hr_recruitment/migrations/9.0.1.0/pre-migration.py
Labels: approved

#2034 [12.0][MIG] res_config_settings_enterprise_remove
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#2043 [12.0][FIX] calendar: Don't remove used types
  addons/calendar/migrations/12.0.1.0/post-migration.py
Labels: approved
