Repository OCA/OpenUpgrade, pull requests merged in 2019-05, with the labels that each got.

#1816 [12.0] base_partner_merge merged in base.
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#1648 9.0 imp account migration by sql
  addons/account/migrations/9.0.1.1/pre-migration.py
Labels: needs review

#1821 [MIG][l10n-brazil] Merged modules
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#1725 [12.0][MIG] hr_recruitment
  addons/hr_recruitment/migrations/12.0.1.0/noupdate_changes.xml
  addons/hr_recruitment/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/hr_recruitment/migrations/12.0.1.0/post-migration.py
  addons/hr_recruitment_survey/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1722 [12.0][MIG] hr_holidays
  addons/hr_holidays/migrations/12.0.1.5/noupdate_changes.xml
  addons/hr_holidays/migrations/12.0.1.5/openupgrade_analysis_work.txt
  addons/hr_holidays/migrations/12.0.1.5/post-migration.py
  addons/hr_holidays/migrations/12.0.1.5/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1679 [12.0][MIG] payment
  addons/payment/migrations/12.0.1.0/noupdate_changes.xml
  addons/payment/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment/migrations/12.0.1.0/post-migration.py
  addons/payment/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1822 [12.0][MIG] website_partner
  addons/website_partner/migrations/12.0.0.1/openupgrade_analysis_work.txt
  addons/website_partner/migrations/12.0.0.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1824 [12.0][MIG] website_hr
  addons/website_hr/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_hr/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1835 [12.0][MIG] payment_*
  addons/payment_adyen/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_authorize/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_buckaroo/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_ogone/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_paypal/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_payumoney/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_sips/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_stripe/migrations/12.0.1.0/noupdate_changes.xml
  addons/payment_stripe/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/payment_stripe/migrations/12.0.1.0/post-migration.py
  addons/payment_transfer/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1846 [12.0][FIX] hr_holidays: assure ids before renaming models
  addons/hr_holidays/migrations/12.0.1.5/post-migration.py
Labels: needs review

#1847 [12.0][FIX] account: assure origin moves before accessing index
  addons/account/migrations/12.0.1.1/post-migration.py
Labels: needs review

#1853 [REM] Remove migrate.py
  odoo/openupgrade/doc/source/after_migration.rst
  odoo/openupgrade/doc/source/index.rst
  odoo/openupgrade/doc/source/intro.rst
  odoo/openupgrade/doc/source/migrate.py.rst
  odoo/openupgrade/doc/source/migration_details.rst
  scripts/migrate.py
Labels: approved

#1845 [12.0][MIG] google_*
  addons/google_calendar/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/google_drive/migrations/12.0.0.2/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review, ready to merge

#1802 [12.0][MIG] l10n_nl
  addons/l10n_nl/migrations/12.0.3.0/openupgrade_analysis_work.txt
  addons/l10n_nl/migrations/12.0.3.0/post-migration.py
  addons/l10n_nl/migrations/12.0.3.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review, ready to merge

#1850 [12.0][FIX] hr_holidays: Avoid trying to repeat followers
  addons/hr_holidays/migrations/12.0.1.5/post-migration.py
Labels: approved, needs review
