Repository OCA/OpenUpgrade, pull requests merged in 2019-08, with the labels that each got.

#1960 [11.0][MIG] sale/purchase_procurement_analytic > procurement_mto_analytic
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1959 [12.0][IMP] mail: remove activity_date_deadline column
  addons/mail/migrations/12.0.1.0/end-migration.py
  addons/mail/migrations/12.0.1.0/openupgrade_analysis_work.txt
Labels: needs review

#1965 [IMP] Do not remove many2many tables
  openerp/addons/base/ir/ir_model.py
Labels: approved

#1970 [10.0][MIG] purchase_fiscal_position_update
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1963 [11.0][FIX] mrp: Consider stock move lines from products that have tracking
  addons/mrp/migrations/11.0.2.0/post-migration.py
Labels: needs review

#1742 [12.0][MIG] l10n_generic_coa
  addons/l10n_generic_coa/migrations/12.0.1.1/noupdate_changes.xml
  addons/l10n_generic_coa/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/l10n_generic_coa/migrations/12.0.1.1/post-lalala.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1975 [11.0][FIX] iap: Don't be auto-installed if you are not going to use any IAP module
  addons/iap/__manifest__.py
Labels: approved

#1980 [12.0][IMP] compare_noupdate_xm_records and [FIX] noupdate_changes
  addons/account/migrations/12.0.1.1/noupdate_changes.xml
  addons/base_address_extended/migrations/12.0.1.0/noupdate_changes.xml
  addons/base_address_extended/migrations/12.0.1.0/post-migration.py
  addons/crm/migrations/12.0.1.0/noupdate_changes.xml
  addons/hr_contract/migrations/12.0.1.0/noupdate_changes.xml
  addons/hr_contract/migrations/12.0.1.0/post-migration.py
  addons/hr_recruitment/migrations/12.0.1.0/noupdate_changes.xml
  addons/mail/migrations/12.0.1.0/noupdate_changes.xml
  addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml
  addons/project/migrations/12.0.1.1/noupdate_changes2.xml
  addons/project/migrations/12.0.1.1/post-migration.py
  addons/sale_expense/migrations/12.0.1.0/noupdate_changes.xml
  addons/sale_expense/migrations/12.0.1.0/post-migration.py
  addons/sale_management/migrations/12.0.1.0/noupdate_changes.xml
  addons/sale_management/migrations/12.0.1.0/post-migration.py
  addons/web/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_sale/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_slides/migrations/12.0.1.0/noupdate_changes.xml
  odoo/openupgrade/doc/source/modules110-120.rst
  scripts/compare_noupdate_xml_records.py
Labels: needs review

#1981 [11.0][FIX] several noupdate_changes
  addons/calendar/migrations/11.0.1.0/noupdate_changes.xml
  addons/mail/migrations/11.0.1.0/noupdate_changes.xml
  addons/point_of_sale/migrations/11.0.1.0.1/noupdate_changes.xml
  addons/point_of_sale/migrations/11.0.1.0.1/post-migration.py
  addons/sale/migrations/11.0.1.1/noupdate_changes.xml
  addons/website_event_sale/migrations/11.0.1.0/noupdate_changes.xml
  addons/website_event_sale/migrations/11.0.1.0/post-migration.py
  addons/website_sale/migrations/11.0.1.0/noupdate_changes.xml
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1984 [ADD] account_asset-> account_asset_management (renamed models)
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1982 [10.0][FIX] several noupdate_changes
  addons/account/migrations/10.0.1.1/noupdate_changes.xml
  addons/event/migrations/10.0.1.0/noupdate_changes.xml
  addons/fleet/migrations/10.0.0.1/noupdate_changes.xml
  addons/fleet/migrations/10.0.0.1/post-migration.py
  addons/hr/migrations/10.0.1.1/noupdate_changes.xml
  addons/hr/migrations/10.0.1.1/post-migration.py
  addons/hr_gamification/migrations/10.0.1.0/noupdate_changes.xml
  addons/hr_gamification/migrations/10.0.1.0/post-migration.py
  addons/hr_recruitment/migrations/10.0.1.0/noupdate_changes.xml
  addons/im_livechat/migrations/10.0.1.0/noupdate_changes.xml
  addons/im_livechat/migrations/10.0.1.0/post-migration.py
  addons/marketing_campaign/migrations/10.0.1.1/noupdate_changes.xml
  addons/marketing_campaign/migrations/10.0.1.1/post-migration.py
  addons/mass_mailing/migrations/10.0.2.0/noupdate_changes.xml
  addons/mass_mailing/migrations/10.0.2.0/post-migration.py
  addons/mrp/migrations/10.0.2.0/noupdate_changes.xml
  addons/point_of_sale/migrations/10.0.1.0.1/noupdate_changes.xml
  addons/project/migrations/10.0.1.1/noupdate_changes.xml
  addons/purchase/migrations/10.0.1.2/noupdate_changes.xml
  addons/sales_team/migrations/10.0.1.0/noupdate_changes.xml
  addons/stock/migrations/10.0.1.1/noupdate_changes.xml
  addons/survey/migrations/10.0.2.0/noupdate_changes.xml
  addons/website_crm/migrations/10.0.2.0/noupdate_changes.xml
  addons/website_crm/migrations/10.0.2.0/post-migration.py
  addons/website_sale/migrations/10.0.1.0/noupdate_changes.xml
  addons/website_slides/migrations/10.0.1.0/noupdate_changes.xml
  odoo/openupgrade/doc/source/modules90-100.rst
Labels: needs review

#1997 [FIX] mass_mailing: remove mass_mailing_security_group record rules
  addons/mass_mailing/migrations/10.0.2.0/post-migration.py
Labels: approved
