Repository OCA/OpenUpgrade, pull requests merged in 2019-06, with the labels that each got.

#1860 [12.0][account] try to link moves with their reversals
  addons/account/migrations/12.0.1.1/post-migration.py
Labels: approved, needs review

#1868 [12.0][MIG] partner statements
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1870 [12.0][FIX] base: add missing xmlid renames for unit of measure
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#1866 [12.0][UPD] openupgrade_records analysis
  addons/account/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/base_address_extended/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/hr/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/hr_holidays/migrations/12.0.1.5/openupgrade_analysis.txt
  addons/l10n_ae/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_it/migrations/12.0.0.2/openupgrade_analysis.txt
  addons/l10n_jp/migrations/12.0.2.1/openupgrade_analysis.txt
  addons/l10n_mn/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_nl/migrations/12.0.3.0/openupgrade_analysis.txt
  addons/l10n_ua/migrations/12.0.1.3/openupgrade_analysis.txt
  addons/l10n_za/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/product/migrations/12.0.1.2/openupgrade_analysis.txt
  addons/project/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/resource/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/sale/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/sale_management/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_quotation_builder/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/sale_timesheet/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/survey/migrations/12.0.3.0/openupgrade_analysis.txt
  addons/test_website/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/website_sale/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_general_log.txt
  odoo/addons/test_convert/migrations/12.0.0.0.1/openupgrade_analysis.txt
Labels: needs review

#1830 [12.0][MIG] website_google_map
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1825 [12.0][MIG] website_mail & website_mail_channel
  addons/website_mail/migrations/12.0.0.1/openupgrade_analysis_work.txt
  addons/website_mail/migrations/12.0.0.1/post-migration.py
  addons/website_mail_channel/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1871 [12.0][IMP] openupgrade_records
  odoo/addons/openupgrade_records/lib/compare.py
Labels: needs review

#1723 [12.0][MIG] hr_timesheet
  addons/hr_timesheet/migrations/12.0.1.0/noupdate_changes.xml
  addons/hr_timesheet/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/hr_timesheet/migrations/12.0.1.0/post-something.py
  addons/hr_timesheet/migrations/12.0.1.0/pre-something.py
  addons/project_timesheet_holidays/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1711 [12.0][MIG] sale
  addons/sale/migrations/12.0.1.1/end-migration.py
  addons/sale/migrations/12.0.1.1/noupdate_changes.xml
  addons/sale/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/sale/migrations/12.0.1.1/post-migration.py
  addons/sale/migrations/12.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1697 [8.0] Fix production order move_lines, move_lines2 migration to one2many
  addons/mrp/migrations/8.0.1.1/post-migrate.py
Labels: approved

#1716 [12.0][MIG] sale_management
  addons/sale_crm/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/sale_management/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/sale_management/migrations/12.0.1.0/post-migration.py
  addons/sale_management/migrations/12.0.1.0/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1878 [12.0][MIG] In Sale : avoid 'product_id' & 'product_uom' non null constraint
  addons/sale/migrations/12.0.1.1/pre-migration.py
Labels: approved

#1881 [12.0][MIG] sale_management: avoid 'product_id' & 'product_uom_id' non null…
  addons/sale_management/migrations/12.0.1.0/pre-migration.py
Labels: needs review

#1880 [12.0][MIG] mrp_bom_structure reports
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved, needs review

#1819 [MIG] website: Handle Bootstrap 3->4 and Less->Scss
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_banner_default_image.png
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_big_picture_default_image.png
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_cover_default_image.jpg
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_image_floating_default_image.png
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_image_text_default_image.png
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_parallax_slider_default_image.png
  addons/website/migrations/12.0.1.0/changed_dummy_images/website.s_text_image_default_image.png
  addons/website/migrations/12.0.1.0/noupdate_changes.xml
  addons/website/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website/migrations/12.0.1.0/post-migration.py
  addons/website/migrations/12.0.1.0/pre-migration.py
Labels: approved, needs review

#1882 [12.0][FIX] product: fix migration of attribute lines
  addons/product/migrations/12.0.1.2/end-migration.py
  addons/product/migrations/12.0.1.2/openupgrade_analysis_work.txt
  addons/product/migrations/12.0.1.2/pre-migration.py
Labels: needs review

#1743 [12.0][MIG] l10n_ch
  addons/l10n_ch/migrations/12.0.10.0/noupdate_changes.xml
  addons/l10n_ch/migrations/12.0.10.0/openupgrade_analysis_work.txt
  addons/l10n_ch/migrations/12.0.10.0/post-migration.py
  addons/l10n_multilang/migrations/12.0.1.1/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1739 [12.0][MIG] sale_timesheet
  addons/sale_timesheet/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1842 [12.0][MIG] website_theme_install
  addons/theme_bootswatch/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/theme_default/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_theme_install/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1826 [12.0][MIG] website_payment
  addons/website_payment/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1827 [12.0][MIG] website_links
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1831 [12.0][MIG] website_gengo
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1828 [12.0][MIG] website_event
  addons/website_event/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_event/migrations/12.0.1.0/pre-lalala.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1836 [12.0][MIG] website_crm
  addons/website_crm/migrations/12.0.2.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1832 [12.0][MIG] website_rating
  addons/website_rating/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1844 [12.0][MIG] base_addess_city & base_address_extended
  addons/base_address_city/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/base_address_extended/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1808 [12.0][MIG] event_sale
  addons/event_sale/migrations/12.0.1.1/noupdate_changes.xml
  addons/event_sale/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/event_sale/migrations/12.0.1.1/post-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1888 [IMP] web_planner: Remove foreign constraints
  addons/web/migrations/12.0.1.0/pre-migration.py
Labels: approved

#1833 [12.0][MIG] website_hr_recruitment
  addons/website_hr_recruitment/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_hr_recruitment/migrations/12.0.1.0/post-migration.py
  addons/website_hr_recruitment/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1834 [12.0][MIG] website_livechat
  addons/website_livechat/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_livechat/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1851 [12.0][FIX] account_voucher: assure company_id in old databases
  addons/account_voucher/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/account_voucher/migrations/12.0.1.0/pre-lol.py
Labels: needs review

#1841 [12.0][MIG] website_crm_partner_assign & website_customer
  addons/website_crm_partner_assign/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_crm_partner_assign/migrations/12.0.1.0/pre-migration.py
  addons/website_customer/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_customer/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1874 [11.0][MIG] website_event_track
  addons/website_event_track/migrations/11.0.1.0/openupgrade_analysis_work.txt
  addons/website_event_track/migrations/11.0.1.0/post-migration.py
  addons/website_event_track/migrations/11.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: needs review

#1843 [12.0][MIG] website_sale
  addons/website_sale/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_sale/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_sale/migrations/12.0.1.0/post-migration.py
  addons/website_sale/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1887 [12.0][MIG] sale_expense: Nothing to do
  addons/sale_expense/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1681 [12.0][MIG] stock & stock_account
  addons/stock/migrations/12.0.1.1/noupdate_changes.xml
  addons/stock/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/12.0.1.1/post-migration.py
  addons/stock/migrations/12.0.1.1/pre-migration.py
  addons/stock_account/migrations/12.0.1.1/noupdate_changes.xml
  addons/stock_account/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/stock_account/migrations/12.0.1.1/post-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1895 [12.0][FIX] account: taxes don't have parent_id field
  addons/account/migrations/12.0.1.1/post-migration.py
Labels: needs review

#1837 [12.0][MIG] website_blog
  addons/website_blog/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_blog/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_blog/migrations/12.0.1.0/post-migration.py
  addons/website_blog/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1857 [12.0][MIG] sale_stock & procurement_jit
  addons/sale_stock/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review
