Repository OCA/OpenUpgrade, pull requests merged in 2019-01, with the labels that each got.

#1563 [12.0][MIG] base_sparse_field
  addons/base_sparse_field/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1682 [11.0][MIG] product_uom
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#1663 [12.0][MIG] event
  addons/event/migrations/12.0.1.0/noupdate_changes.xml
  addons/event/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/event/migrations/12.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1664 [12.0][MIG] mass_mailing
  addons/mass_mailing/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/12.0.2.0/post-migration.py
  addons/mass_mailing/migrations/12.0.2.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1554 [12.0][MIG] rating
  addons/rating/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review, ready to merge

#1673 [12.0][MIG] social_media
  addons/social_media/migrations/12.0.0.1/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1684 [12.0][MIG] sms
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1675 [12.0][MIG] hr
  addons/hr/migrations/12.0.1.1/noupdate_changes.xml
  addons/hr/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/hr/migrations/12.0.1.1/post-migration.py
  addons/hr/migrations/12.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1575 [12.0][MIG] survey
  addons/survey/migrations/12.0.3.0/noupdate_changes.xml
  addons/survey/migrations/12.0.3.0/openupgrade_analysis_work.txt
  addons/survey/migrations/12.0.3.0/post-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1678 [12.0][FIX] base, mail: minor fixes
  addons/mail/migrations/12.0.1.0/end-migration.py
  odoo/addons/base/migrations/12.0.1.3/post-migration.py
Labels: needs review

#1555 [12.0][MIG] phone_validation & crm_phone_validation
  addons/phone_validation/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1556 [12.0][MIG] pad
  addons/pad/migrations/12.0.2.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1557 [12.0][MIG] transifex
  addons/transifex/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1562 [12.0][MIG] auth_ldap
  addons/auth_ldap/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1689 [12.0][MIG] auth_oauth
  addons/auth_oauth/migrations/12.0.1.0/noupdate_changes.xml
  addons/auth_oauth/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/auth_oauth/migrations/12.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1676 [12.0][MIG] maintenance
  addons/maintenance/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/maintenance/migrations/12.0.1.0/post-migration.py
  addons/maintenance/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1635 [11.0] stock account: migrate account_move_ids, value, remaining_value and remaining_qty for stock.moves
  addons/stock_account/migrations/11.0.1.1/openupgrade_analysis_work.txt
  addons/stock_account/migrations/11.0.1.1/post-migration.py
Labels: help wanted, needs review

#1633 [11.0][FIX] stock: add move lines from inventory moves
  addons/stock/migrations/11.0.1.1/post-migration.py
Labels: needs review

#1574 [12.0][MIG] lunch
  addons/lunch/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1688 [12.0][MIG] hr_attendance
  addons/hr_attendance/migrations/12.0.2.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1629 [11.0][MIG] mrp_repair
  addons/mrp_repair/migrations/11.0.1.0/noupdate_changes.xml
  addons/mrp_repair/migrations/11.0.1.0/openupgrade_analysis_work.txt
  addons/mrp_repair/migrations/11.0.1.0/post-migration.py
  addons/mrp_repair/migrations/11.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: approved, needs review

#1691 [12.0][MIG] calendar_sms
  addons/calendar_sms/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1690 [12.0][MIG] im_livechat & crm_livechat
  addons/im_livechat/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1692 [12.0][MIG] Some auto_install modules
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review
