Repository OCA/OpenUpgrade, pull requests merged in 2019-04, with the labels that each got.

#1793 [12.0][FIX] Avoid error is product module is not installed
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#1769 [12.0][FIX] project: some fixes
  addons/project/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/project/migrations/12.0.1.1/post-migration.py
  addons/project/migrations/12.0.1.1/pre-migration.py
Labels: needs review

#1730 [12.0][MIG] base_vat
  addons/base_vat/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1801 [FIX] base: Preserve passwords on new admin user
  odoo/addons/base/migrations/12.0.1.3/end-migration.py
Labels: approved

#1726 [12.0][MIG] hr_org_chart
  addons/hr_org_chart/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, needs review

#1803 [12.0][MIG] base_iban
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1806 [12.0][MIG] account_cancel
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#1731 [12.0][MIG] base_vat_autocomplete -> partner_autocomplete
  addons/partner_autocomplete/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1685 [12.0][MIG] website
  addons/website/migrations/12.0.1.0/noupdate_changes.xml
  addons/website/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website/migrations/12.0.1.0/post-migration.py
  addons/website/migrations/12.0.1.0/pre-migration.py
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#1807 [12.0][MIG] membership & association
  addons/membership/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved
