Repository OCA/OpenUpgrade, pull requests merged in 2019-12, with the labels that each got.

#2097 [12][MIG] product_expiry: Migration script (nothing todo)
  addons/product_expiry/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#2099 [11.0][ADD] hr_timesheet_attendance: Nothing to do
  addons/hr_timesheet_attendance/migrations/11.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules100-110.rst
Labels: approved

#2090 [12.0][MIG] Rename of sale_procurement_group_by_required_date module
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#2092 [12.0][IMP] base: Faster ir_translation removal
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: approved

#2105 [FIX] stock_putaway_product: Product template strategies were not taken into account
  addons/stock/migrations/12.0.1.1/post-migration.py
Labels: approved

#1734 [12.0][MIG] repair
  addons/repair/migrations/12.0.1.0/noupdate_changes.xml
  addons/repair/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/repair/migrations/12.0.1.0/post-migration.py
  addons/repair/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#2111 [12.0][UPD] Documentation
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#2102 [12.0][MIG] website_sale_wishlist: Migration script
  addons/website_sale_wishlist/migrations/12.0.1.0/noupdate_changes.xml
  addons/website_sale_wishlist/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/website_sale_wishlist/migrations/12.0.1.0/post-migration.py
  addons/website_sale_wishlist/migrations/12.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#2104 [IMP] purchase: Optimize migration in SQL
  .travis.yml
  addons/purchase/migrations/9.0.1.2/end-migration.py
  addons/purchase/migrations/9.0.1.2/post-migration.py
  addons/purchase/migrations/9.0.1.2/pre-migration.py
Labels: approved, ready to merge

#2114 [IMP] account_voucher: Optimize computed field doing it via SQL
  addons/account_voucher/migrations/9.0.1.0/post-migration.py
  addons/account_voucher/migrations/9.0.1.0/pre-migration.py
Labels: approved

#2134 [12.0] update upstream e7984c4968c
  addons/account/models/account_invoice.py
  addons/account/tests/test_product_id_change.py
  addons/calendar/models/res_partner.py
  addons/google_account/models/google_service.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mrp/wizard/change_production_qty.py
  addons/payment_paypal/models/payment.py
  addons/project/controllers/portal.py
  addons/project/views/project_portal_templates.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_packing.py
  addons/stock_account/models/product.py
  addons/website_partner/models/res_partner.py
  addons/website_sale_stock/controllers/main.py
  doc/_extensions/odoo_ext/layout.html
  doc/cla/individual/federicolatorre.md
  doc/cla/individual/lilee115.md
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/base/migrations/12.0.1.3/noupdate_changes.xml
  odoo/tests/common.py
  odoo/tools/mail.py
Labels: needs review

#2128 [12.0][UPD] openupgrade_analysis
  addons/l10n_dk/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_id/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/l10n_lt/migrations/12.0.1.0.0/openupgrade_analysis.txt
  addons/l10n_mn/migrations/12.0.1.0/openupgrade_analysis.txt
  addons/stock_account/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/test_website/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_general_log.txt
Labels: needs review

#2139 [13.0][UPD] openupgrade_analysis
  addons/account/migrations/13.0.1.1/openupgrade_analysis.txt
  addons/base_automation/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/im_livechat/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/l10n_at/migrations/13.0.3.0/openupgrade_analysis.txt
  addons/l10n_ch/migrations/13.0.10.0/openupgrade_analysis.txt
  addons/l10n_cl/migrations/13.0.3.0/openupgrade_analysis.txt
  addons/l10n_dk/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/l10n_es/migrations/13.0.4.0/openupgrade_analysis.txt
  addons/l10n_id/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/l10n_il/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/l10n_it/migrations/13.0.0.2/openupgrade_analysis.txt
  addons/l10n_lt/migrations/13.0.1.0.0/openupgrade_analysis.txt
  addons/l10n_no/migrations/13.0.2.0/openupgrade_analysis.txt
  addons/l10n_vn/migrations/13.0.2.0/openupgrade_analysis.txt
  addons/mrp_account/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/pos_kitchen_printer/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/purchase_product_matrix/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/sale/migrations/13.0.1.1/openupgrade_analysis.txt
  addons/sale_product_matrix/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/stock_account/migrations/13.0.1.1/openupgrade_analysis.txt
  addons/stock_picking_batch/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/survey/migrations/13.0.3.0/openupgrade_analysis.txt
  addons/website/migrations/13.0.1.0/openupgrade_analysis.txt
  addons/website_crm/migrations/13.0.2.1/openupgrade_analysis.txt
  odoo/addons/base/migrations/13.0.1.3/openupgrade_general_log.txt
Labels: needs review

#2031 [12.0][FIX] sale_timesheet: Set qty_delivered_method
  addons/sale/migrations/12.0.1.1/post-migration.py
  addons/sale_timesheet/migrations/12.0.1.0/openupgrade_analysis_work.txt
Labels: approved, needs review, ready to merge
