Repository OCA/OpenUpgrade, pull requests merged in 2020-07, with the labels that each got.

#2361 [11.0][IMP] base: rename 'mass_mailing_event'
  odoo/addons/base/migrations/11.0.1.3/pre-migration.py
Labels: approved, bot is merging ⏳

#2364 [11.0][IMP] stock: Don't break on quant merge errors
  addons/stock/migrations/11.0.1.1/end-migration.py
Labels: bot is merging ⏳

#2365 [10.0][FIX] hr_timesheet: Create project for all possible timesheets
  addons/hr_timesheet/migrations/10.0.1.0/post-migration.py
Labels: approved

#2367 [11.0][FIX] base: Adjust res.partner.category colors
  odoo/addons/base/migrations/11.0.1.3/post-migration.py
Labels: bot is merging ⏳
