Repository OCA/OpenUpgrade, pull requests merged in 2020-11, with the labels that each got.

#2441 [13.0][FIX] account: don't update date on nondraft move lines
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#2438 [13.0][MIG] board
  addons/board/migrations/13.0.1.0/noupdate_changes.xml
  addons/board/migrations/13.0.1.0/openupgrade_analysis.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2278 [13.0][MIG] payment
  addons/payment/migrations/13.0.1.0/noupdate_changes.xml
  addons/payment/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/payment/migrations/13.0.1.0/post-migration.py
  addons/payment/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2435 [13.0][MIG] base_iban
  addons/base_iban/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2434 [13.0][MIG] account_facturx
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2285 [13.0][MIG] hr
  addons/hr/migrations/13.0.1.1/noupdate_changes.xml
  addons/hr/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/hr/migrations/13.0.1.1/post-migration.py
  addons/hr/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2286 [13.0][MIG] hr_contract
  addons/hr_contract/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/hr_contract/migrations/13.0.1.0/post-migration.py
  addons/hr_contract/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2287 [13.0][MIG] hr_holidays
  addons/hr_holidays/migrations/13.0.1.5/noupdate_changes.xml
  addons/hr_holidays/migrations/13.0.1.5/openupgrade_analysis_work.txt
  addons/hr_holidays/migrations/13.0.1.5/post-migration.py
  addons/hr_holidays/migrations/13.0.1.5/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2383 [13.0][MIG] payment_transfer
  addons/payment_transfer/migrations/13.0.1.0/noupdate_changes.xml
  addons/payment_transfer/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/payment_transfer/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2280 [13.0][MIG] project
  addons/project/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/project/migrations/13.0.1.1/post-migration.py
  addons/project/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review, ready to merge

#2419 [13.0][MIG] l10n_es
  addons/l10n_es/migrations/13.0.4.0/openupgrade_analysis_work.txt
  addons/l10n_es/migrations/13.0.4.0/post-migration.py
  addons/l10n_es/migrations/13.0.4.0/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2297 [13.0][MIG] sale
  addons/sale/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/sale/migrations/13.0.1.1/post-migration.py
  addons/sale/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2437 [13.0][MIG] base_automation
  addons/base_automation/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2374 [13.0][MIG] website_blog
  addons/website_blog/migrations/13.0.1.0/noupdate_changes.xml
  addons/website_blog/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/website_blog/migrations/13.0.1.0/post-migration.py
  addons/website_blog/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, approved, bot is merging ⏳, needs review, ready to merge

#2305 [13.0][MIG] survey
  addons/survey/migrations/13.0.3.0/openupgrade_analysis_work.txt
  addons/survey/migrations/13.0.3.0/post-migration.py
  addons/survey/migrations/13.0.3.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2447 [13.0][account][fix] Improve the mapping of invoice line data to move lines.
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#2277 [13.0][MIG] crm
  addons/crm/migrations/13.0.1.0/noupdate_changes.xml
  addons/crm/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/crm/migrations/13.0.1.0/post-migration.py
  addons/crm/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2291 [13.0][MIG] hr_timesheet
  addons/hr_timesheet/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/hr_timesheet/migrations/13.0.1.0/post-migration.py
  addons/hr_timesheet/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, needs review

#2388 [13.0][MIG] sale_timesheet
  addons/sale_timesheet/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/sale_timesheet/migrations/13.0.1.0/post-migration.py
  addons/sale_timesheet/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2455 [13.0][FIX] utm: avoid foreign_key error in utm_tag_rel table
  addons/utm/migrations/13.0.1.0/post-migration.py
  addons/utm/migrations/13.0.1.0/pre-migration.py
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
Labels: approved, needs review
