Repository OCA/OpenUpgrade, pull requests merged in 2020-02, with the labels that each got.

#2187 [11.0][UPD] noupdate_changes.xml files
  addons/account/migrations/11.0.1.1/noupdate_changes.xml
  addons/account_asset/migrations/11.0.1.0/noupdate_changes.xml
  addons/base_gengo/migrations/11.0.1.0/noupdate_changes.xml
  addons/calendar/migrations/11.0.1.0/noupdate_changes.xml
  addons/crm/migrations/11.0.1.0/noupdate_changes.xml
  addons/delivery/migrations/11.0.1.0/noupdate_changes.xml
  addons/event/migrations/11.0.1.0/noupdate_changes.xml
  addons/fetchmail/migrations/11.0.1.0/noupdate_changes.xml
  addons/gamification/migrations/11.0.1.0/noupdate_changes.xml
  addons/gamification_sale_crm/migrations/11.0.1.0/noupdate_changes.xml
  addons/google_drive/migrations/11.0.0.2/noupdate_changes.xml
  addons/hr_expense/migrations/11.0.2.0/noupdate_changes.xml
  addons/l10n_be_invoice_bba/migrations/11.0.1.2/noupdate_changes.xml
  addons/l10n_ca/migrations/11.0.1.0/noupdate_changes.xml
  addons/l10n_ch/migrations/11.0.10.0/noupdate_changes.xml
  addons/l10n_cn_small_business/migrations/11.0.1.8/noupdate_changes.xml
  addons/l10n_de_skr03/migrations/11.0.3.0/noupdate_changes.xml
  addons/l10n_de_skr04/migrations/11.0.3.0/noupdate_changes.xml
  addons/l10n_do/migrations/11.0.2.0/noupdate_changes.xml
  addons/l10n_generic_coa/migrations/11.0.1.1/noupdate_changes.xml
  addons/l10n_gt/migrations/11.0.3.0/noupdate_changes.xml
  addons/l10n_hn/migrations/11.0.0.2/noupdate_changes.xml
  addons/l10n_mx/migrations/11.0.2.0/noupdate_changes.xml
  addons/l10n_nl/migrations/11.0.3.0/noupdate_changes.xml
  addons/l10n_pt/migrations/11.0.0.011/noupdate_changes.xml
  addons/l10n_ve/migrations/11.0.1.0/noupdate_changes.xml
  addons/mail/migrations/11.0.1.0/noupdate_changes.xml
  addons/mass_mailing/migrations/11.0.2.0/noupdate_changes.xml
  addons/membership/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_adyen/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_authorize/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_buckaroo/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_ogone/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_payumoney/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_stripe/migrations/11.0.1.0/noupdate_changes.xml
  addons/payment_transfer/migrations/11.0.1.0/noupdate_changes.xml
  addons/project/migrations/11.0.1.1/noupdate_changes.xml
  addons/stock/migrations/11.0.1.1/noupdate_changes.xml
  addons/website_crm/migrations/11.0.2.0/noupdate_changes.xml
  addons/website_slides/migrations/11.0.1.0/noupdate_changes.xml
  odoo/addons/base/migrations/11.0.1.3/noupdate_changes.xml
Labels: needs review

#2147 [FIX] missing report type and tree type
  openerp/addons/base/migrations/8.0.1.3/pre-migration.py
Labels: approved, ready to merge

#2192 [12.0][MIG] l10n_us
  addons/l10n_us/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/l10n_us/migrations/12.0.1.1/post-migration.py
  addons/l10n_us/migrations/12.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: needs review

#2194 [FIX] install master version of openupgradelib
  requirements.txt
Labels: approved

#2196 [9.0][FIX] base: Assign company of the rate to the currency company
  openerp/addons/base/migrations/9.0.1.3/openupgrade_analysis_work.txt
  openerp/addons/base/migrations/9.0.1.3/pre-migration.py
Labels: approved

#2205 [ADD] base, base_setup, web, web_editor, web_unsplash
  addons/base_setup/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/base_setup/migrations/13.0.1.0/post-migration.py
  addons/web/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/web/migrations/13.0.1.0/post-migration.py
  addons/web_editor/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/web_editor/migrations/13.0.1.0/post-migration.py
  addons/web_unsplash/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/web_unsplash/migrations/13.0.1.1/pre-migration.py
  odoo/addons/base/migrations/13.0.1.3/noupdate_changes.xml
  odoo/addons/base/migrations/13.0.1.3/openupgrade_analysis_work.txt
  odoo/addons/base/migrations/13.0.1.3/post-migration.py
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: work in progress

#2201 [IMP] Performance of new partner stored computed fields
  odoo/addons/base/migrations/10.0.1.3/pre-migration.py
Labels: approved
