Repository OCA/OpenUpgrade, pull requests merged in 2020-10, with the labels that each got.

#2410 [MIG][12.0] pos_reprint and pos_discount
  addons/pos_discount/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: bot is merging ⏳

#2275 [13.0][MIG] account
  addons/account/migrations/13.0.1.1/end-migration.py
  addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/13.0.1.1/post-migration.py
  addons/account/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2422 [13.0][FIX] base: assure new categories are noupdate = 1 and not deleted after migration
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
Labels: needs review
