Repository OCA/OpenUpgrade, pull requests merged in 2020-03, with the labels that each got.

#2210 [ADD] Additions to the base migration
  odoo/addons/base/migrations/13.0.1.3/end-migration.py
  odoo/addons/base/migrations/13.0.1.3/openupgrade_analysis_work.txt
  odoo/addons/base/migrations/13.0.1.3/post-migration.py
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
Labels: approved, ready to merge

#2215 [13.0] Set migration status for simple module without changes
  addons/base_import/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/http_routing/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/web_tour/migrations/13.0.0.1/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2221 [13.0][IMP] web_favicon functionality merged in base
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#2224 [11.0][FIX] base: avoid unique_name_per_day sql constrain
  odoo/addons/base/migrations/11.0.1.3/post-migration.py
  odoo/addons/base/migrations/11.0.1.3/pre-migration.py
Labels: approved, needs review

#2229 [13.0][ADD] google_* modules
  addons/google_drive/migrations/13.0.0.2/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: merged 🎉

#2239 [13.0][ADD] iap module
  addons/iap/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/iap/migrations/13.0.1.0/post-migration.py
  addons/iap/migrations/13.0.1.0/pre-migration.py
Labels: approved

#2254 [12.0][FIX] base: add remove_tables_fks
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#2247 [13.0][ADD] uom module
  addons/uom/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/uom/migrations/13.0.1.0/post-migration.py
  addons/uom/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2223 [13.0][IMP] base
  odoo/addons/base/migrations/13.0.1.3/noupdate_changes.xml
  odoo/addons/base/migrations/13.0.1.3/openupgrade_analysis_work.txt
  odoo/addons/base/migrations/13.0.1.3/post-migration.py
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#2216 [13.0][ADD] mail module
  addons/mail/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/mail/migrations/13.0.1.0/post-migration.py
  addons/mail/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: bot is merging ⏳, needs review

#2259 [13.0][MIG] analytic
  addons/analytic/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/analytic/migrations/13.0.1.1/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review
