Repository OCA/OpenUpgrade, pull requests merged in 2020-08, with the labels that each got.

#2380 [13.0][FIX] base: Avoid possible issues with missing categories
  odoo/addons/base/migrations/13.0.1.3/pre-migration.py
Labels: needs review

#2389 [9.0][IMP] Correct qty_delivered for phantom bom lines
  addons/sale/migrations/9.0.1.0/post-migration.py
  addons/sale_mrp/migrations/9.0.1.0/post-migrate.py
  openerp/openupgrade/deferred_90.py
Labels: approved

#2372 [FIX] utm: avoid issue '"utm_stage" does not exist'
  addons/utm/migrations/13.0.1.0/pre-migration.py
Labels: approved

#2394 [FIX] utm: avoidng issue `column utm_stage.sequence does not exist`
  addons/utm/migrations/13.0.1.0/pre-migration.py
Labels: bot is merging ⏳

#2399 [10.0] [FIX] Regression: im_livechat: records in pre migration might not exist
  addons/im_livechat/migrations/10.0.1.0/pre-migration.py
Labels: bot is merging ⏳, bug
