Repository OCA/OpenUpgrade, pull requests merged in 2020-04, with the labels that each got.

#2258 [13.0][MIG] utm
  addons/utm/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/utm/migrations/13.0.1.0/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2262 [13.0][MIG] product
  addons/product/migrations/13.0.1.2/noupdate_changes.xml
  addons/product/migrations/13.0.1.2/openupgrade_analysis_work.txt
  addons/product/migrations/13.0.1.2/post-migration.py
  addons/product/migrations/13.0.1.2/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: bot is merging ⏳, needs review

#2282 [12.0][ADD] stock_picking_batch: Nothing to do
  addons/stock_picking_batch/migrations/12.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: bot is merging ⏳

#2264 [13.0][MIG] resource
  addons/resource/migrations/13.0.1.1/noupdate_changes.xml
  addons/resource/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/resource/migrations/13.0.1.1/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2265 [13.0][MIG] calendar
  addons/calendar/migrations/13.0.1.0/noupdate_changes.xml
  addons/calendar/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/calendar/migrations/13.0.1.0/post-migration.py
  addons/calendar/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2274 [13.0][MIG] link_tracker
  addons/link_tracker/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/link_tracker/migrations/13.0.1.0/post-migration.py
  addons/link_tracker/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2266 [13.0][MIG] digest
  addons/digest/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/digest/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, approved, needs review

#2300 [13.0][MIG] mail_bot
  addons/mail_bot/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2276 [13.0][MIG] sales_team
  addons/sales_team/migrations/13.0.1.0/noupdate_changes.xml
  addons/sales_team/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/sales_team/migrations/13.0.1.0/post-migration.py
  addons/sales_team/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review, ready to merge

#2273 [13.0][MIG] mass_mailing
  addons/mass_mailing/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/13.0.2.0/post-migration.py
  addons/mass_mailing/migrations/13.0.2.0/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2283 [13.0][MIG] fleet
  addons/fleet/migrations/13.0.0.1/openupgrade_analysis_work.txt
  addons/fleet/migrations/13.0.0.1/post-migration.py
  addons/fleet/migrations/13.0.0.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2318 [FIX] account: migration 8->9, wrong sql to determine tax in account.invoice.tax
  addons/account/migrations/9.0.1.1/post-migration.py
Labels: approved

#2312 [ADD] rename web_advanced_filters to web_advanced_filter
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved, ready to merge

#2325 [FIX] auth_ldap: remove view ref from action
  addons/auth_ldap/migrations/11.0.1.0/post-migration.py
Labels: bot is merging ⏳
