Repository OCA/OpenUpgrade, pull requests merged in 2020-12, with the labels that each got.

#2465 [13.0][FIX] hr_attendance: load noupdate_changes
  addons/hr_attendance/migrations/13.0.2.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2466 [13.0][FIX] base_address_extended: load noupdate_changes
  addons/base_address_extended/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2468 [11.0][UPD] base: noupdate_changes.xml file up to day
  odoo/addons/base/migrations/11.0.1.3/noupdate_changes.xml
Labels: needs review

#2467 [12.0][UPD] noupdate_changes.xml files up to day
  addons/board/migrations/12.0.1.0/noupdate_changes.xml
  addons/calendar/migrations/12.0.1.0/noupdate_changes.xml
  addons/delivery/migrations/12.0.1.0/noupdate_changes.xml
  addons/event/migrations/12.0.1.0/noupdate_changes.xml
  addons/mail/migrations/12.0.1.0/noupdate_changes.xml
  addons/mrp/migrations/12.0.2.0/noupdate_changes.xml
  addons/project/migrations/12.0.1.1/noupdate_changes.xml
  addons/website_sale/migrations/12.0.1.0/noupdate_changes.xml
  odoo/addons/base/migrations/12.0.1.3/noupdate_changes.xml
Labels: needs review

#2470 [12.0][FIX] stock: consider also inactive warehouses
  addons/mrp/migrations/12.0.2.0/post-migration.py
Labels: approved, needs review

#2480 [12.0][FIX] account: reference_type is used in account_payment_order module
  addons/account/migrations/12.0.1.1/pre-migration.py
Labels: needs review

#2483 [13.0] [FIX] account migration: create invoice_payment_state in pre-migration
  addons/account/migrations/13.0.1.1/pre-migration.py
Labels: needs review

#2484 [11.0] update upstream 8090621a00b
  addons/mail/models/mail_followers.py
Labels: needs review

#2489 Fix bug: account group_show_line_subtotals_tax_included / excluded #2487
  addons/account/migrations/13.0.1.1/noupdate_changes.xml
Labels: approved
