Repository OCA/OpenUpgrade, pull requests merged in 2021-05, with the labels that each got.

#2706 [ADD] apriory: Change of name of edi modules
  openupgrade_scripts/apriori.py
Labels: approved

#2310 [13.0][MIG] purchase
  addons/purchase/migrations/13.0.1.2/noupdate_changes.xml
  addons/purchase/migrations/13.0.1.2/openupgrade_analysis_work.txt
  addons/purchase/migrations/13.0.1.2/post-migration.py
  addons/purchase/migrations/13.0.1.2/pre-migration.py
  addons/purchase_stock/__manifest__.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review, ready to merge

#2720 [13.0][FIX] account: use refund_invoice_id to fill reversed_entry_id
  addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved, needs review

#2725 [13.0][MIG] website_livechat: finish migration
  addons/website_livechat/migrations/13.0.1.0/noupdate_changes.xml
  addons/website_livechat/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/website_livechat/migrations/13.0.1.0/post-migration.py
  addons/website_livechat/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2728 [12.0][IMP] mail: less nested query
  addons/mail/migrations/12.0.1.0/end-migration.py
Labels: needs review

#2714 [10.0][IMP] recompute invoice_status for po's with products invoiced by delivered quantities
  addons/purchase/migrations/10.0.1.2/post-migration.py
Labels: needs review

#2732 [12.0][FIX] sale_stock: put migration file into numeric folder
  addons/sale_stock/migrations/12.0.1.0/pre-migration.py
Labels: bot is merging ⏳, needs review

#2386 [13.0][MIG] payment_adyen
  addons/payment_adyen/migrations/13.0.1.0/noupdate_changes.xml
  addons/payment_adyen/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/payment_adyen/migrations/13.0.1.0/post-migration.py
  addons/payment_adyen/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2385 [13.0][MIG] payment_stripe
  addons/payment_stripe/migrations/13.0.1.0/noupdate_changes.xml
  addons/payment_stripe/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/payment_stripe/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2200 [9.0][FIX] set currency_id to account.configurable_chart_template
  addons/account/migrations/9.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/9.0.1.1/pre-migration.py
Labels: work in progress

#2733 [13.0][FIX] account: use old customer/supplier fields for ranks
  addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved, needs review

#2735 [13.0][IMP] account: null zip range fiscal position
  addons/account/migrations/13.0.1.1/pre-migration.py
Labels: needs review

#2737 [11.0][OU-FIX] mrp: fix wrong creation of stock move lines
  addons/mrp/migrations/11.0.2.0/post-migration.py
Labels: approved

#2343 [11.0][IMP] Have postgres process the update
  addons/stock_account/migrations/11.0.1.1/post-migration.py
Labels: needs review

#2739 [13.0][FIX] account: Don't have duplicated invoice line links
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#2745 [13.0][IMP] product: Empty company_id
  addons/product/migrations/13.0.1.2/post-migration.py
Labels: approved
