Repository OCA/OpenUpgrade, pull requests merged in 2021-01, with the labels that each got.

#2493 [11.0][MIG] stock: maintain relation of stock move line and stock pack operation models
  addons/base_vat_autocomplete/models/res_partner.py
  addons/stock/migrations/11.0.1.1/post-migration.py
Labels: needs review

#2306 [13.0][MIG] stock
  addons/stock/migrations/13.0.1.1/end-migration.py
  addons/stock/migrations/13.0.1.1/noupdate_changes.xml
  addons/stock/migrations/13.0.1.1/noupdate_changes2.xml
  addons/stock/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/13.0.1.1/post-migration.py
  addons/stock/migrations/13.0.1.1/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, bot is merging ⏳, needs review, ready to merge

#2281 [13.0][MIG] event
  addons/event/migrations/13.0.1.0/noupdate_changes.xml
  addons/event/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/event/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, bot is merging ⏳, needs review, ready to merge

#2498 [13.0][DEL] Remove coverage
  .github/workflows/test.yml
Labels: bot is merging ⏳

#2500 [13.0] [FIX] Account: populate the journal_id field of move lines
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved, bot is merging ⏳
