Repository OCA/OpenUpgrade, pull requests merged in 2021-02, with the labels that each got.

#2512 [13.0][FIX] account: read fields when computing balance for draft invoices
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved, bot is merging ⏳, needs review

#2502 [11.0][FIX] stock: use a global route to avoid creating too many rules
  addons/stock/migrations/11.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/11.0.1.1/post-migration.py
  addons/stock/migrations/11.0.1.1/pre-migration.py
Labels: approved, needs review, ready to merge

#2518 [13.0][ADD] stock_picking_batch: Migration scripts
  addons/stock_picking_batch/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/stock_picking_batch/migrations/13.0.1.0/post-migration.py
  addons/stock_picking_batch/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2505 [13.0][MIG] l10n_de
  addons/l10n_de/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2517 [13.0][ADD] account_payment: Nothing to do
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2520 [11.0][IMP] rating: prepopulate stored field on mail_message
  addons/rating/migrations/11.0.1.0/pre-migration.py
Labels: approved

#2299 [13.0][MIG] website
  addons/website/migrations/13.0.1.0/noupdate_changes.xml
  addons/website/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/website/migrations/13.0.1.0/post-migration.py
  addons/website/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2496 [FIX] website_blog: fix blog and post covers
  addons/website_blog/migrations/13.0.1.0/noupdate_changes.xml
  addons/website_blog/migrations/13.0.1.0/post-migration.py
  addons/website_blog/migrations/13.0.1.0/pre-migration.py
Labels: needs review

#2507 [13.0][MIG] l10n_de_skr04
  addons/l10n_de_skr04/migrations/13.0.3.0/openupgrade_analysis_work.txt
  addons/l10n_de_skr04/migrations/13.0.3.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2373 [13.0][MIG] website_mail
  addons/website_mail/migrations/13.0.0.1/openupgrade_analysis_work.txt
  addons/website_mail/migrations/13.0.0.1/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2529 [13.0][MIG] pad_project
  addons/pad_project/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: bot is merging ⏳, needs review

#2514 [13.0][FIX] account: post-migration: simple speed up of some queries
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#2525 [13.0][MIG] sale_expense
  addons/sale_expense/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/sale_expense/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, approved, needs review

#2439 [13.0][MIG] hr_expense
  addons/hr_expense/migrations/13.0.2.0/noupdate_changes.xml
  addons/hr_expense/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/hr_expense/migrations/13.0.2.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2321 [13.0][MIG] im_livechat
  addons/im_livechat/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/im_livechat/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2519 [IMP] stock: adapt records instead of re-create
  addons/stock/migrations/13.0.1.1/end-migration.py
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: approved, needs review

#2543 [13.0][ADD] sale_stock: Nothing to do
  addons/sale_stock/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, approved

#2544 [12.0][FIX] sale_stock: Move incoterms_id content to incoterm_id
  addons/sale_stock/migrations/12.0.1.0/openupgrade_analysis_work.txt
  addons/sale_stock/migrations/pre-migration.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved

#2546 [13.0][IMP-OU] account: improve performance creating amount_tax_company_signed
  addons/account/migrations/13.0.1.1/pre-migration.py
Labels: approved, needs review

#2557 [FIX] sale: don't change prefix of sale sequence
  addons/sale/migrations/13.0.1.1/noupdate_changes.xml
Labels: needs review

#2563 [12.0][UPD] openupgrade_analysis
  addons/hr_attendance/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/l10n_be/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/l10n_ch/migrations/12.0.11.0/openupgrade_analysis.txt
  addons/l10n_co/migrations/12.0.0.8/openupgrade_analysis.txt
  addons/l10n_es/migrations/12.0.4.0/openupgrade_analysis.txt
  addons/l10n_fr/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/l10n_it_edi/migrations/12.0.0.3/openupgrade_analysis.txt
  addons/l10n_jp/migrations/12.0.2.2/openupgrade_analysis.txt
  addons/l10n_mx/migrations/12.0.2.0/openupgrade_analysis.txt
  addons/l10n_nl/migrations/12.0.3.0/openupgrade_analysis.txt
  addons/l10n_nl/migrations/12.0.3.0/post-migration.py
  addons/l10n_nl/migrations/12.0.3.0/pre-migration.py
  addons/pos_cash_rounding/migrations/12.0.1.0.0/openupgrade_analysis.txt
  addons/sale/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/snailmail/migrations/12.0.0.1/openupgrade_analysis.txt
  addons/stock/migrations/12.0.1.1/openupgrade_analysis.txt
  addons/website_membership/migrations/12.0.1.0/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/noupdate_changes.xml
  odoo/addons/base/migrations/12.0.1.3/openupgrade_analysis.txt
  odoo/addons/base/migrations/12.0.1.3/openupgrade_general_log.txt
Labels: needs review

#2561 [13.0][FIX] stock: must delete model data of location_procurement
  addons/stock/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: needs review

#2558 [12.0][FIX] barcodes: assure nomenclature_id
  addons/barcodes/migrations/12.0.2.0/pre-migration.py
Labels: approved, needs review

#2531 [9.0][FIX] Don't (also) insert child taxes as parent taxes
  addons/account/migrations/9.0.1.1/post-migration.py
Labels: approved

#2284 [13.0][MIG] gamification
  addons/gamification/migrations/13.0.1.0/noupdate_changes.xml
  addons/gamification/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/gamification/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2320 [13.0][MIG] sms
  addons/sms/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/sms/migrations/13.0.2.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review, ready to merge

#2556 [13.0][MIG] website_theme_install
  addons/website_theme_install/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2553 [13.0][MIG] website_links
  addons/website_links/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2549 [13.0][MIG] crm_livechat
  addons/crm_livechat/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2319 [13.0][MIG] snailmail
  addons/snailmail/migrations/13.0.0.1/openupgrade_analysis_work.txt
  addons/snailmail/migrations/13.0.0.1/post-migration.py
  addons/snailmail/migrations/13.0.0.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review, ready to merge

#2433 [13.0][MIG] l10n_multilang
  addons/l10n_multilang/migrations/13.0.1.1/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2579 [13.0][OU-FIX] account: consider anglo_saxon_accounting
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved, needs review

#2292 [13.0][MIG] l10n_generic_coa
  addons/l10n_generic_coa/migrations/13.0.1.1/noupdate_changes.xml
  addons/l10n_generic_coa/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/l10n_generic_coa/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2580 [13.0][FIX] Don't reset module states on exception
  odoo/modules/registry.py
Labels: needs review

#2534 [13.0][MIG] website_livechat
  addons/website_livechat/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2294 [13.0][MIG] website_sale
  addons/website_sale/migrations/13.0.1.0/noupdate_changes.xml
  addons/website_sale/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/website_sale/migrations/13.0.1.0/post-migration.py
  addons/website_sale/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2555 [13.0][MIG] website_form_project
  addons/website_form_project/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, ready to merge

#2290 [13.0][ADD] hr_recruitment
  addons/hr_recruitment/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/hr_recruitment/migrations/13.0.1.0/post-migration.py
  addons/hr_recruitment/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2574 [13.0][MIG] website_sale_management: Migration script
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2532 [13.0][MIG] website_hr_recruitment
  addons/website_hr_recruitment/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency

#2542 [13.0][ADD] account_analytic_default: Migration scripts
  addons/account_analytic_default/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/account_analytic_default/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Blocked by dependency, approved

#2578 [13.0][MIG] mass_mailing_sale: Migration script
  addons/mass_mailing_sale/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved

#2592 [13.0][OU-ADD] website_snippet_anchor: Merged website_snippet_anchor to website
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#2596 [13.0][FIX] website_sale: Reorder website_sequence according new criteria
  addons/website_sale/migrations/13.0.1.0/pre-migration.py
Labels: approved
