Repository OCA/OpenUpgrade, pull requests merged in 2021-11, with the labels that each got.

#2954 [FIX] replace print by logger
  odoo/openupgrade/openupgrade_log.py
Labels: approved

#2947 [14.0][FIX] base: delete duplicated properties and disable filters
  openupgrade_scripts/scripts/base/14.0.1.3/end-migration.py
  openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py
Labels: needs review

#2957 [13.0][IMP] mrp: removed useless join
  addons/mrp/migrations/13.0.2.0/post-migration.py
Labels: needs review

#2955 [14.0][IMP] project: pre-create computed stored fields
  openupgrade_scripts/scripts/project/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/project/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/project/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#2378 [13.0][MIG] stock_landed_costs
  addons/stock_landed_costs/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/stock_landed_costs/migrations/13.0.1.1/post-migration.py
  addons/stock_landed_costs/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review, approved

#2964 [ADD] main coverage file
  .pre-commit-config.yaml
  build_openupgrade_docs
  docsource/modules140-150.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/account_edi/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/base/15.0.1.3/upgrade_general_log.txt
  openupgrade_scripts/scripts/crm_iap_enrich/15.0.1.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/crm_iap_mine/15.0.1.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_eu_oss/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_se/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/mail_plugin/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/payment/15.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/payment_mollie/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/payment_ogone/15.0.2.0/noupdate_changes.xml
  openupgrade_scripts/scripts/payment_ogone/15.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_timesheet/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/website/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/website_event_booth/15.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/website_event_exhibitor/15.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/website_event_exhibitor/15.0.1.1/upgrade_analysis.txt
Labels: approved

#2672 [13.0][FIX] product: still missing attributes and relations
  addons/mrp/migrations/13.0.2.0/post-migration.py
  addons/product/migrations/13.0.1.2/openupgrade_analysis_work.txt
  addons/product/migrations/13.0.1.2/post-migration.py
  addons/product/migrations/13.0.1.2/pre-migration.py
Labels: needs review, approved

#2974 [13.0][FIX] purchase_mrp: fill bom_line_id in moves
  addons/purchase_mrp/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review, approved

#2975 [13.0][MIG] muk_dms*: Rename to dms.
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#2908 [IMP] account: Migration of grouped invoice lines. Allow to import notes and sections
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review, approved

#2976 [14.0][UPD] upgrade_analysis files
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/auth_totp/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/base/14.0.1.3/upgrade_general_log.txt
  openupgrade_scripts/scripts/fleet/14.0.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/upgrade_analysis.txt
  openupgrade_scripts/scripts/hr_presence/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/hr_recruitment/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/l10n_cl/14.0.3.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_co/14.0.0.8/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_es/14.0.5.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_es_edi_sii/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_gcc_invoice/14.0.1.0.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_in_purchase/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_it/14.0.0.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_pe/14.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_sa_invoice/14.0.1.0.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_vn/14.0.2.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/l10n_vn/14.0.2.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/mrp/14.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/portal/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/product_expiry/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sms/14.0.2.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/stock/14.0.1.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_base_automation/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_mail/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_new_api/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/website/14.0.1.0/noupdate_changes.xml
Labels: needs review

#2813 [14.0][MIG] lunch
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/lunch/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/lunch/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/lunch/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/lunch/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2988 [13.0][MIG] hr_payroll: Move to OCA payroll
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2987 [13.0][FIX] product: assure combination indices are unique
  addons/product/migrations/13.0.1.2/pre-migration.py
Labels: needs review
