Repository OCA/OpenUpgrade, pull requests merged in 2021-12, with the labels that each got.

#2921 [9.0][FIX] project: Migrated date fields from account.analytic.account to …
  addons/project/migrations/9.0.1.1/openupgrade_analysis_work.txt
  addons/project/migrations/9.0.1.1/post-migration.py
Labels: needs review, approved

#2995 [IMP] apriori file odoo/account_budget renamed into OCA/account-budgeting/account_budget_oca
  odoo/addons/openupgrade_records/lib/apriori.py
  odoo/openupgrade/doc/source/modules110-120.rst
Labels: approved, bot is merging ⏳

#2741 [14.0][MIG] account
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳

#2704 [14.0][MIG] base_vat
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/base_vat/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2822 [14.0][MIG] partner_autocomplete
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/partner_autocomplete/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, Nothing to do

#2700 [14.0][MIG] base_iban
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/base_iban/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, Nothing to do

#2742 [14.0][MIG] payment
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/payment/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/payment/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2789 [14.0][MIG] hr
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/hr/14.0.1.1/post-migrate.py
  openupgrade_scripts/scripts/hr/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#2864 [14.0][MIG] hr_recruitment
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_recruitment/14.0.1.0/post-migration.py
Labels: needs review

#2823 [14.0][MIG] hr_org_chart
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_org_chart/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, Nothing to do

#2996 [14.0][MIG] hr_contract
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_contract/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_contract/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_contract/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2865 [14.0][MIG] hr_timesheet
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved

#2866 [14.0][MIG] hr_holidays
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/post-migration.py
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/upgrade_analysis_work.txt
Labels: needs review

#3008 [14.0][FIX] hr: wrong call of delete_records_safely_by_xml_id
  openupgrade_scripts/scripts/hr/14.0.1.1/post-migrate.py
Labels: bug

#2999 [FIX] base : prevent double membership to 'portal' and 'user' group that is forbidden in V12
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review, approved, ready to merge

#3000 [10.0][FIX] base: Merge records through SQL
  odoo/addons/base/migrations/10.0.1.3/post-migration.py
Labels: needs review

#3006 [13.0][OU-ADD] stock_forecast_report: Merged in stock
  addons/stock/migrations/13.0.1.1/pre-migration.py
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#3013 [14.0][UPD] upgrade_analysis: add constraints
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/account_edi/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/account_edi_facturx/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/account_edi_proxy_client/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/adyen_platforms/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/base/14.0.1.3/upgrade_analysis.txt
  openupgrade_scripts/scripts/base/14.0.1.3/upgrade_general_log.txt
  openupgrade_scripts/scripts/calendar/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/coupon/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/crm/14.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/crm/14.0.1.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/crm/14.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/delivery/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/gamification/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/google_calendar/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_ar/14.0.3.5/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_gcc_pos/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_in/14.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_it_edi/14.0.0.3/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_sa_pos/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/mrp/14.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/point_of_sale/14.0.1.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/rating/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/rating/14.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sale_management/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_project/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_timesheet/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sales_team/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/stock/14.0.1.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/survey/14.0.3.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_impex/14.0.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_inherit/14.0.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_new_api/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/test_uninstall/14.0.0.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/uom/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/uom/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/uom/14.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/website_event_questions/14.0.1.1/upgrade_analysis.txt
Labels: needs review, bot is merging ⏳
