Repository OCA/OpenUpgrade, pull requests merged in 2021-06, with the labels that each got.

#2346 [13.0][MIG] mrp
  addons/mrp/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/mrp/migrations/13.0.2.0/post-migration.py
  addons/mrp/migrations/13.0.2.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2724 [13.0][MIG] event_sale
  addons/event_sale/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/event_sale/migrations/13.0.1.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2744 [14.0][ADD] github CI
  .github/workflows/documentation.yml
  .github/workflows/flake.yml
  .github/workflows/test.yml
  .old-travis.yml
  .travis.yml
  build_openupgrade_docs
  doc/__init__.py
  doc/fetch_coverage.sh
Labels: help wanted

#2660 [14.0][MIG] mail
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/mail/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/mail/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/mail/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/mail/14.0.1.0/upgrade_analysis_work.txt
Labels: Waiting

#2666 [14.0][MIG] uom
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/uom/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/uom/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/uom/14.0.1.0/upgrade_analysis_work.txt
Labels: Waiting, approved, ready to merge

#2673 [14.0][MIG] web
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/web/14.0.1.0/upgrade_analysis_work.txt
Labels: Waiting, approved, ready to merge

#2668 [14.0][MIG] utm
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/utm/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/utm/14.0.1.0/upgrade_analysis_work.txt
Labels: Waiting, approved, ready to merge

#2681 [14.0][MIG] bus
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/bus/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#2682 [14.0][MIG] note
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/note/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/note/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/note/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#2684 [14.0][MIG] board
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/board/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/board/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#2685 [14.0][MIG] contacts
  doc/source/modules130-140.rst
Labels: approved, ready to merge

#2759 14.0 Fixed FileNotFoundError given by a typo
  openupgrade_scripts/scripts/product/14.0.1.2/post-migration.py
Labels: approved

#2758 14.0 fix calendar migration
  doc/source/modules130-140.rst
  openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/calendar/14.0.1.0/pre-migration.py
Labels: needs review

#2757 [11.0][IMP] stock: fix company on quants for customers/supplier location
  addons/stock/migrations/11.0.1.1/pre-migration.py
Labels: bot is merging ⏳, needs review

#2763 [14.0][FIX] utm: use env instead of cr in delete xmlids
  openupgrade_scripts/scripts/utm/14.0.1.0/post-migration.py
Labels: needs review

#2756 [14.0] CI: no flake8; yaml line length
  .github/workflows/documentation.yml
  .github/workflows/flake.yml
  .github/workflows/test.yml
Labels: needs review

#2767 [DOC] add banner images + url website
  openupgrade_framework/README.rst
  openupgrade_framework/__manifest__.py
  openupgrade_framework/readme/DESCRIPTION.rst
  openupgrade_framework/readme/DEVELOP.rst
  openupgrade_framework/static/description/banner.png
  openupgrade_framework/static/description/index.html
  openupgrade_scripts/__manifest__.py
  openupgrade_scripts/static/description/banner.png
  openupgrade_scripts/static/description/index.html
Labels: approved

#2770 [13.0][FIX] sale_mrp: fill bom_line_id in moves
  addons/mrp/migrations/13.0.2.0/post-migration.py
  addons/sale_mrp/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2773 [11.0][FIX] sale_stock: fill sale_id of procurement groups without moves
  addons/sale_stock/migrations/11.0.1.0/pre-migration.py
Labels: approved, needs review, ready to merge

#2784 [DOC][FIX]Bad directory reference
  docsource/development.rst
Labels: approved

#2787 [14.0][FIX] github workflow test.yml: adapt to docsource change
  .github/workflows/test.yml
Labels: needs review

#2772 [9.0][IMP] migrate bic numbers
  addons/account/migrations/9.0.1.1/pre-migration.py
Labels: approved
