Repository OCA/OpenUpgrade, pull requests merged in 2021-07, with the labels that each got.

#2796 [9.0][FIX] use_parent_address <=> partner type 'contact'
  openerp/addons/base/migrations/9.0.1.3/post-migration.py
Labels: approved

#2802 [14.0][MIG] http_routing
  docsource/modules130-140.rst
Labels: needs review

#2791 [14.0][MIG] auth_signup
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/auth_signup/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/auth_signup/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2803 [14.0][MIG] portal
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/portal/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2806 [14.0][MIG] fetchmail
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/fetchmail/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2670 [14.0][MIG] base_automation
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/base_automation/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/base_automation/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2807 [14.0][MIG] gamification
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/gamification/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/gamification/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/gamification/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/gamification/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2820 [14.0][ADD] new migration analysis files
  openupgrade_scripts/scripts/account_edi_proxy_client/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_ar/14.0.3.4/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_ar_website_sale/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_de_purchase/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_de_repair/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_de_sale/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_de_stock/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_it_edi_sdicoop/14.0.0.3/upgrade_analysis.txt
Labels: needs review

#2809 [14.0][MIG] phone_validation
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/phone_validation/14.0.2.0/upgrade_analysis_work.txt
Labels: needs review

#2810 [14.0][MIG] barcodes
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/barcodes/14.0.2.0/upgrade_analysis_work.txt
Labels: needs review

#2811 [14.0][MIG] mail_bot
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/mail_bot/14.0.1.2/upgrade_analysis_work.txt
Labels: needs review

#2804 [14.0][Add] digest: Migration Script.
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/digest/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/digest/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/digest/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#2812 [14.0][MIG] link_tracker
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/link_tracker/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#2816 [14.0][MIG] pad
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/pad/14.0.2.0/upgrade_analysis_work.txt
Labels: needs review

#2827 [14.0][FIX] rating: update rating value
  openupgrade_scripts/scripts/rating/14.0.1.0/pre-migration.py
Labels: needs review

#2830 [14.0][MIG] auth_oauth
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/auth_oauth/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/auth_oauth/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2315 [13.0][MIG] maintenance
  addons/maintenance/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/maintenance/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2723 [13.0][MIG] project_timesheet_holidays
  addons/project_timesheet_holidays/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: approved, needs review

#2826 [14.0][MIG] project
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/project/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/project/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/project/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/project/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#2837 [13.0][MIG] purchase_requisition_stock
  addons/purchase_requisition_stock/migrations/13.0.1.2/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2838 [14.0][MIG] pad_project
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/pad_project/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2691 [13.0][FIX]stock_account: prevent empty layers to be created
  addons/stock_account/migrations/13.0.1.1/post-migration.py
Labels: approved, needs review, ready to merge

#2817 [14.0][MIG] iap
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/iap/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/iap/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#2304 [13.0][MIG] lunch
  addons/lunch/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/lunch/migrations/13.0.1.0/post-migration.py
  addons/lunch/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2828 [14.0][MIG] crm
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/crm/14.0.1.2/noupdate_changes.xml
  openupgrade_scripts/scripts/crm/14.0.1.2/post-migration.py
  openupgrade_scripts/scripts/crm/14.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/crm/14.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sales_team/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sales_team/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2836 [14.0][MIG] event
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/event/14.0.1.3/noupdate_changes.xml
  openupgrade_scripts/scripts/event/14.0.1.3/post-migration.py
  openupgrade_scripts/scripts/event/14.0.1.3/pre-migration.py
  openupgrade_scripts/scripts/event/14.0.1.3/upgrade_analysis_work.txt
Labels: needs review

#2832 [14.0][MIG] note_pad
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/note_pad/14.0.0.1/upgrade_analysis_work.txt
Labels: needs review

#2850 [11.0][OUFIX] base: migrate ir_default condition
  odoo/addons/base/migrations/11.0.1.3/post-migration.py
Labels: approved

#2847 [14.0][UPD] apriori + analysis
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/base/14.0.1.3/upgrade_general_log.txt
  openupgrade_scripts/scripts/coupon/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/coupon/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/coupon/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_coupon/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_coupon_delivery/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/survey/14.0.3.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/website_sale_coupon/14.0.1.0/upgrade_analysis.txt
Labels: needs review
