Repository OCA/OpenUpgrade, pull requests merged in 2021-09, with the labels that each got.

#2900 [11.0] update upstream 5b281c3cfbb
  odoo/fields.py
  odoo/tools/sql.py
Labels: needs review

#2855 [14.0][MIG] event_crm
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/event_crm/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#2854 [14.0][MIG] im_livechat
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/im_livechat/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/im_livechat/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/im_livechat/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳

#2907 [FIX] account: Check parent in order to fill the data
  addons/account/migrations/13.0.1.1/end-migration.py
Labels: needs review, approved

#2913 [13.0][FIX] delivery: invoice_policy
  addons/delivery/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/delivery/migrations/13.0.1.0/post-migration.py
Labels: approved

#2916 [13.0][OU-FIX] account: Avoid empty string on name
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: approved

#2918 [13.0] apriori: merge several modules in account_menu
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review, bot is merging ⏳

#2919 [IMP] account: Do the transformation of messages on a single query, not one for each record
  addons/account/migrations/13.0.1.1/post-migration.py
  addons/account/migrations/13.0.1.1/pre-migration.py
Labels: approved
