Repository OCA/OpenUpgrade, pull requests merged in 2022-02, with the labels that each got.

#2326 [13.0][MIG] point_of_sale
  addons/point_of_sale/migrations/13.0.1.0.1/end-migration.py
  addons/point_of_sale/migrations/13.0.1.0.1/noupdate_changes.xml
  addons/point_of_sale/migrations/13.0.1.0.1/openupgrade_analysis_work.txt
  addons/point_of_sale/migrations/13.0.1.0.1/post-migration.py
  addons/point_of_sale/migrations/13.0.1.0.1/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#2382 [13.0][MIG] pos_sale
  addons/pos_sale/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/pos_sale/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3117 [12.0][FIX] mrp: only fill new data pickings pbm_type_id and sam_type_id
  addons/mrp/migrations/12.0.2.0/openupgrade_analysis_work.txt
  addons/mrp/migrations/12.0.2.0/post-migration.py
Labels: needs review

#3130 [13.0][UPD] apriori: rename iot modules
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3128 [12.0][FIX] stock: avoid duplicated putaway strategies (fixup)
  addons/stock/migrations/12.0.1.1/post-migration.py
Labels: needs review

#3122 [13.0][FIX] stock: assign correct location to quants/packages (multicompany)
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: work in progress, needs review

#3131 [13.0][FIX] stock: assign correct location to quants/packages (multicompany) [fixup]
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3132 [13.0][FIX] stock: handle module stock_production_lot_multi_company migration
  addons/stock/migrations/13.0.1.1/post-migration.py
  addons/stock/migrations/13.0.1.1/pre-migration.py
Labels: needs review

#2381 [13.0][MIG] website_event_track
  addons/website_event_track/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/website_event_track/migrations/13.0.1.0/post-migration.py
  addons/website_event_track/migrations/13.0.1.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3058 [14.0][FIX] account.partial.reconcile compute missing fields
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3086 [13.0][FIX] account restrict_mode_hash_table more restrictive
  addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review, approved

#3142 [12.0][FIX] mrp: make the hook in migration work
  addons/mrp/migrations/12.0.2.0/post-migration.py
Labels: needs review

#3143 [12.0][FIX] *: lift obsolete many2one constraints
  addons/account/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/12.0.1.1/pre-migration.py
  addons/sale/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/sale/migrations/12.0.1.1/pre-migration.py
  addons/stock/migrations/12.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/12.0.1.1/pre-migration.py
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#2840 [14.0][MIG] website
  docsource/modules130-140.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/website/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved

#3102 [MIG][14.0] website_mail: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_mail/14.0.0.1/post-migration.py
  openupgrade_scripts/scripts/website_mail/14.0.0.1/upgrade_analysis_work.txt
Labels: needs review

#3147 [14.0][FIX] account: add hooks to avoid hardcoding lock dates
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: needs review

#3148 [12.0][FIX] stock: assure merged rules have same locations
  addons/stock/migrations/12.0.1.1/post-migration.py
Labels: needs review

#3149 [14.0][UPD] upgrade_analysis: add gmail modules
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/fetchmail_gmail/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/fetchmail_gmail/14.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/google_gmail/14.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/google_gmail/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3150 [14.0][FIX] account: fill partner_bank_id in statement line moves
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#3152 [13.0][ADD] hr_expense: Added a function that migrates the tax tags (accoun…
  addons/hr_expense/migrations/13.0.2.0/post-migration.py
Labels: needs review

#3155 [14.0][OU-FIX] Migration scripts were not run during install
  docsource/modules130-140.rst
  openupgrade_framework/odoo_patch/odoo/modules/migration.py
  openupgrade_scripts/scripts/sale_project/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_project/14.0.1.0/upgrade_analysis_work.txt
Labels: approved

#3109 [MIG][14.0]sale_project: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_project/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_project/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review
