Repository OCA/OpenUpgrade, pull requests merged in 2022-12, with the labels that each got.

#3368 [MIG][15.0] base_iban : nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/base_iban/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳

#3373 [MIG][15.0] account_edi_facturx: nothing to do
  docsource/modules140-150.rst
Labels: merged 🎉

#3378 [MIG][15.0] base_vat: nothing to do
  docsource/modules140-150.rst
Labels: needs review

#3318 [MIG][15.0] mass_mailing_sale: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/mass_mailing_sale/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3658 [14.0][OU-FIX] hr_timesheet: Delete obsolete view
  openupgrade_scripts/scripts/hr_timesheet/14.0.1.0/pre-migration.py
Labels: approved

#3306 [MIG][15.0] hr_timesheet: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_timesheet/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_timesheet/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3646 [14.0][OU-ADD] website_sale_delivery: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_sale_delivery/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3666 [14.0][OU-ADD] website_form_recaptcha: Merged in website_form
  openupgrade_scripts/apriori.py
Labels: needs review
