Repository OCA/OpenUpgrade, pull requests merged in 2022-07, with the labels that each got.

#3236 [OU-ADD] project_stage_state > project_task_stage_state
  openupgrade_scripts/apriori.py
Labels: needs review, approved, ready to merge

#3370 [15.0][MIG] board : nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/board/15.0.1.0/upgrade_analysis_work.txt
Labels: approved

#3366 [MIG][15.0] attachment_indexation: nothing to do
  docsource/modules140-150.rst
Labels: approved

#3369 [MIG][15.0] base_import : nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/base_import/15.0.2.0/upgrade_analysis_work.txt
Labels: approved

#3282 [MIG][15.0] utm: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/utm/15.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/utm/15.0.1.1/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3273 [MIG][15.0] mail: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py
  openupgrade_scripts/scripts/mail/15.0.1.5/pre-migration.py
  openupgrade_scripts/scripts/mail/15.0.1.5/upgrade_analysis_work.txt
Labels: approved

#3449 [15.0][IMP] apriori: add more oca merged_modules
  openupgrade_scripts/apriori.py
Labels: needs review, approved

#3448 [14.0][OU-ADD] website_event_registration_free_text: Merged to website_event_registration
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website_event_questions/14.0.1.1/pre-migration.py
Labels: approved

#3450 [IMP][15.0] openupgrade_framework: to not crash, simply not deactivating the views
  openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
Labels: approved, ready to merge

#3348 [15.0][IMP] base: override to not raise an exception
  openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
Labels: needs review

#3462 [15.0][MIG] http_routing: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3465 [15.0][MIG] mail_bot: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/mail_bot/15.0.1.2/upgrade_analysis_work.txt
Labels: Nothing to do

#3289 [14.0][MIG] website_forum
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_forum/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/website_forum/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_forum/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_forum/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3081 [MIG][14.0] mass_mailing_slides: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3101 [MIG][14.0] website_mail_channel: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_mail_channel/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_mail_channel/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3090 [MIG][14.0] website_livechat: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_livechat/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_livechat/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_livechat/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3091 [MIG][14.0] website_hr_recruitment: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_hr_recruitment/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_hr_recruitment/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_hr_recruitment/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3076 [MIG][14.0] l10n_dz: nothing to do
  docsource/modules130-140.rst
Labels: Nothing to do

#3074 [MIG][14.0] l10n_dk: nothing to do
  docsource/modules130-140.rst
Labels: Nothing to do

#2819 [14.0][MIG] survey
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/survey/14.0.3.2/noupdate_changes.xml
  openupgrade_scripts/scripts/survey/14.0.3.2/post-migration.py
  openupgrade_scripts/scripts/survey/14.0.3.2/pre-migration.py
  openupgrade_scripts/scripts/survey/14.0.3.2/upgrade_analysis_work.txt
Labels: needs review

#3468 [14.0][MIG] website_slides_forum
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_slides_forum/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3469 [14.0][MIG] website_sms
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3470 [14.0][MIG] website_slides_survey
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_slides_survey/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_slides_survey/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3471 [14.0][MIG] website_mass_mailing
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_mass_mailing/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3472 [14.0][MIG] website_links
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#2790 [14.0][MIG] product_expiry
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/product_expiry/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/product_expiry/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/product_expiry/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3473 [14.0][MIG] website_crm_sms
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#2861 [14.0][MIG] coupon (from sale_coupon)
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/coupon/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/coupon/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/coupon/14.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sale_coupon/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2868 [14.0][MIG] account_debit_note
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account_debit_note/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3474 [14.0][MIG] website_crm_livechat
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_crm_livechat/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3069 [MIG][14.0] hr_skills: Migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_skills/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_skills/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3068 [MIG][14.0] hr_recruitment_survey: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_recruitment_survey/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2829 [13.0][MIG] crm_iap_lead (from crm_reveal)
  addons/crm_iap_lead/migrations/13.0.1.0/noupdate_changes.xml
  addons/crm_iap_lead/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/crm_iap_lead/migrations/13.0.1.0/post-migration.py
  addons/crm_iap_lead/migrations/13.0.1.0/pre-migration.py
  addons/crm_iap_lead_website/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3475 [14.0][MIG] stock_landed_costs
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/stock_landed_costs/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/stock_landed_costs/14.0.1.1/openupgrade_analysis_work.txt
  openupgrade_scripts/scripts/stock_landed_costs/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock_landed_costs/14.0.1.1/pre-migration.py
Labels: needs review

#3476 [14.0][MIG] iap_crm
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/iap_crm/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3052 [MIG][14.0] crm_iap_lead_enrich: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/crm_iap_lead_enrich/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/crm_iap_lead_enrich/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#3479 [15.0][MIG] web_editor: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/web_editor/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3275 [MIG][15.0] resource: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/resource/15.0.1.1/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3281 [MIG][15.0] maintenance: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/maintenance/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/maintenance/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/maintenance/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3296 [ADD] 13.0 - l10n_fr_fec : nothing to do
  addons/l10n_fr_fec/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Nothing to do

#3367 [15.0][MIG] base_automation : nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/base_automation/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge, Nothing to do

#3333 [MIG][15.0] hr_fleet: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_fleet/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_fleet/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3362 [MIG][15.0] note: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/note/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3324 [MIG][15.0]rating: add mig script v15
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/rating/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/rating/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/rating/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3383 [MIG][15.0] digest: nothing to do
  docsource/modules140-150.rst
Labels: approved, ready to merge

#3483 [15.0][MIG] fetchmail: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3361 [MIG][15.0] im_livechat: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/im_livechat/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3372 [15.0][MIG] contacts : Nothing to do
  docsource/modules140-150.rst
Labels: approved, ready to merge, Nothing to do

#3392 [MIG][15.0] iap: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/iap/15.0.1.1/upgrade_analysis_work.txt
Labels: Nothing to do

#3420 [MIG][15.0] iap_mail: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3277 [MIG][15.0] phone_validation: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/phone_validation/15.0.2.1/upgrade_analysis_work.txt
Labels: approved, ready to merge, Nothing to do

#3356 [MIG][15.0] snailmail: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/snailmail/15.0.0.3/upgrade_analysis_work.txt
Labels: Nothing to do

#3484 [15.0][MIG] auth_topt_portal: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/auth_totp_portal/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3377 [MIG][15.0] base_geolocalize: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3427 [MIG][15.0] microsoft_account: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3485 [15.0][MIG] link_tracker: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3424 [MIG][15.0] mail_bot_hr: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3421 [MIG][15.0] im_livechat_mail_bot: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3386 [MIG][15.0] google_account: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3488 [15.0][MIG] google_recaptcha: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/google_recaptcha/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#2849 [13.0][MIG] event_sms
  addons/event_sms/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review, Nothing to do

#3408 [MIG][15.0] google_drive: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/google_drive/15.0.0.2/upgrade_analysis_work.txt
Labels: Nothing to do

#3403 [MIG][15.0] google_spreadsheet: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/google_spreadsheet/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3411 [MIG][15.0] hr_maintenance: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3490 [15.0][FIX] sales_team: put more coherent create_uid, create_date
  openupgrade_scripts/scripts/sales_team/15.0.1.1/post-migration.py
Labels: needs review

#3440 [MIG][15.0] social_media: nothing to do
  docsource/modules140-150.rst
Labels: Nothing to do

#3430 [MIG][15.0] partner_autocomplete: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/partner_autocomplete/15.0.1.1/upgrade_analysis_work.txt
Labels: Nothing to do

#3355 [MIG][15.0] hr_attendance: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_attendance/15.0.2.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3402 [MIG][15.0] hr_skills: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_skills/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3494 [FIX] add new module coverage file to ignore
  .gitignore
Labels: bot is merging ⏳

#2994 [14.0][MIG] website_sale
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_sale/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/website_sale/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_sale/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_sale/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3100 [MIG][14.0] website_membership: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_membership/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_membership/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_membership/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3105 [MIG][14.0] website_event_sale: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_event_sale/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_event_sale/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_event_sale/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3039 [MIG][14.0] microsoft_account: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/microsoft_account/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3038 [MIG][14.0] microsoft_calendar: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/microsoft_calendar/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2910 [14.0][MIG] website_sale_stock
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3053 [MIG][14.0] crm_iap_lead_website: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/crm_iap_lead_website/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/crm_iap_lead_website/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#2998 [14.0][MIG] delivery
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/delivery/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/delivery/14.0.1.0/openupgrade_analysis_work.txt
  openupgrade_scripts/scripts/delivery/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/delivery/14.0.1.0/pre-migration.py
Labels: needs review

#3498 [14.0][MIG] hr_gamification: nothing to do
  docsource/modules130-140.rst
Labels: bot is merging ⏳
