Repository OCA/OpenUpgrade, pull requests merged in 2022-11, with the labels that each got.

#3612 [15.0][IMP] apriori: survey_description to survey
  openupgrade_scripts/apriori.py
Labels: approved

#3613 [13.0][UPD] apriori product_active_propagate is now native in product V13.
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3600 [16.0][IMP] apriori: initial filling
  openupgrade_scripts/apriori.py
Labels: needs review, bot is merging ⏳

#3619 [14.0][FIX] Dotfiles + remove incorrect files
  .copier-answers.yml
  .old-travis.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#3607 [14.0][ADD] apriory: Change name of edi_voxel_* modules to edi_voxel_*_oca
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge

#3625 [OU] hr_holidays: recompute duration_display in script in order to avoid errors for changes on the selection
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/end-migration.py
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/upgrade_analysis_work.txt
Labels: approved

#3565 [15.0][MIG] crm_iap_lead: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/crm_iap_mine/15.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/crm_iap_mine/15.0.1.2/upgrade_analysis_work.txt
Labels: needs review
