Repository OCA/OpenUpgrade, pull requests merged in 2022-10, with the labels that each got.

#3573 [14.0][IMP] apriori: hr_holidays_gantt_calendar -> hr_holidays_gantt
  openupgrade_scripts/apriori.py
Labels: needs review

#3492 [15.0][MIG] product: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/product/15.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/product/15.0.1.2/upgrade_analysis_work.txt
Labels: needs review, approved, bot is merging ⏳

#3576 [15.0][IMP] apriori: stock_barcode_mobile -> stock_barcode
  openupgrade_scripts/apriori.py
Labels: needs review

#3581 [15.0][IMP] base: avoid spamming html conversion for partners
  openupgrade_scripts/scripts/base/15.0.1.3/pre-migration.py
Labels: needs review

#3500 [15.0][MIG] event
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/event/15.0.1.6/post-migration.py
  openupgrade_scripts/scripts/event/15.0.1.6/pre-migration.py
  openupgrade_scripts/scripts/event/15.0.1.6/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3493 [DOC] Add simple use case 'field renaming'
  docsource/development.rst
  docsource/use_cases/field_renaming.rst
Labels: approved, ready to merge

#3501 [15.0][MIG] event_sms
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/event/15.0.1.6/pre-migration.py
  openupgrade_scripts/scripts/event_sms/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/event_sms/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3591 [14.0][OU-FIX] account: Switch state to cancel on dangling payments
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: approved

#3585 [15][mail] Avoid crash when migrating a database from v8
  openupgrade_scripts/scripts/mail/15.0.1.5/pre-migration.py
Labels: approved

#3590 [ADD] rename account_menu into account_usability
  openupgrade_scripts/apriori.py
Labels: needs review, bot is merging ⏳

#3594 update apriori OCA base_geolocalize_openstreetmap merged into base_geolocalize
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3596 [13.0] update apriori : sale_disable_inventory_check merged into sale_stock
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3597 [13.0] web_tree_resize_column merged in web
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3598 [13.0] apriori : web_widget_float_formula merged in web
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3599 [IMP] bi_sql_editor_aggregate merged into bi_sql_editor
  openupgrade_scripts/apriori.py
Labels: needs review

#3595 [FIX] base: Uninstall l10n_it_edi to avoid conflict with l10n_it_fatturapa
  openupgrade_scripts/scripts/base/14.0.1.3/end-migration.py
  openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py
Labels: approved, ready to merge
