Repository OCA/OpenUpgrade, pull requests merged in 2022-06, with the labels that each got.

#3267 [MIG][15.0] uom: nothinh to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/uom/15.0.1.0/upgrade_analysis_work.txt
Labels: approved

#3271 [MIG][15.0] analytic: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/analytic/15.0.1.1/upgrade_analysis_work.txt
Labels: approved

#3222 [13.0][FIX] survey: make use of merge_models
  addons/survey/migrations/13.0.3.0/post-migration.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3208 [14.0][MIG] website_profile
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_profile/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3207 [14.0][MIG] website_form
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_form/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge, Nothing to do

#3145 [12.0][REM] l10n_nl: Stop deletion of tag 3b
  addons/l10n_nl/migrations/12.0.3.0/post-migration.py
Labels: needs review

#3265 [MIG][15.0] web: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/web/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/web/15.0.1.0/upgrade_analysis_work.txt
Labels: approved

#3209 [14.0][MIG] website_google_map
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3291 [14.0][MIG] website_crm
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_crm/14.0.2.1/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3103 [MIG][14.0] website_crm_partner_assign: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_crm_partner_assign/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_crm_partner_assign/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_crm_partner_assign/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3104 [MIG][14.0] website_customer: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_customer/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_customer/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_customer/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#2936 [14.0][MIG] website_event
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_event/14.0.1.1/post-migrate.py
  openupgrade_scripts/scripts/website_event/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/website_event/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#3107 [MIG][14.0] website_event_track: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_event_track/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/website_event_track/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#2722 [13.0][MIG] gamification_sale_crm
  addons/gamification_sale_crm/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3064 [MIG][14.0] google_spreadsheet: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3065 [MIG][14.0] hr_fleet: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_fleet/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3043 [MIG][14.0] account_lock: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#2839 [14.0][MIG] transifex
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/transifex/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3071 [MIG][14.0] hr_work_entry: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_work_entry/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2848 [13.0][MIG] crm_sms
  addons/crm_sms/migrations/13.0.1.0/openupgrade_analysis_work.txt
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review, Nothing to do

#2846 [14.0][MIG] iap_mail
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/iap_mail/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2858 [14.0][MIG] sms
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sms/14.0.2.1/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2825 [14.0][MIG] snailmail
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/snailmail/14.0.0.3/upgrade_analysis_work.txt
Labels: Nothing to do

#2923 [14.0][MIG] auth_ldap: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/auth_ldap/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, Nothing to do

#3067 [MIG][14.0] hr_presence: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_presence/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_presence/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2857 [14.0][MIG] event_sms
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/event_sms/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/event_sms/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2856 [14.0][MIG] crm_sms
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/crm_sms/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/crm_sms/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3084 [MIG][14.0] mass_mailing_sms: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/mass_mailing_sms/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3093 [MIG][14.0] stock_sms: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/stock_sms/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/stock_sms/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved

#3063 [MIG][14.0] gamification_sale_crm: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/gamification_sale_crm/14.0.1.0/post-migration.py
Labels: needs review

#3066 [MIG][14.0] hr_holidays_attendance: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3295 [14.0][MIG] website_payment
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_payment/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3269 [MIG][15.0] web_tour: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/web_tour/15.0.0.1/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3270 [MIG][15.0] bus: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/bus/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3325 [13.0][FIX] stock: avoid triggering prefix change on sequence code filling
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3330 [IMP][15.0] openupgrade_framework: tracking number of rows per table before and after the migration
  openupgrade_framework/odoo_patch/odoo/modules/__init__.py
  openupgrade_framework/odoo_patch/odoo/modules/loading.py
Labels: approved

#3322 [14.0][FIX] fleet: remove obsolete table fks
  .github/workflows/test.yml
  openupgrade_framework/odoo_patch/odoo/modules/graph.py
  openupgrade_framework/readme/DESCRIPTION.rst
  openupgrade_scripts/scripts/fleet/14.0.0.1/pre-migration.py
Labels: needs review

#3327 [MIG] sale_purchase
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_purchase/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3301 [MIG][15.0] barcodes: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/barcodes/15.0.2.0/upgrade_analysis_work.txt
Labels: approved

#3329 [13.0][UPD] apriori: repair_calendar_view -> base_repair
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3184 [13.0][ADD] l10n_nl: Added migration script for the Dutch localization module.
  addons/l10n_nl/migrations/13.0.3.0/post-migration.py
Labels: approved
