Repository OCA/OpenUpgrade, pull requests merged in 2022-01, with the labels that each got.

#2843 [14.0][MIG] sale
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/sale/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/sale/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/sale/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#2845 [14.0][MIG] sale_management
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_management/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/sale_management/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_management/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_management/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#2877 [14.0][MIG] sale_crm
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_crm/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳, Nothing to do

#2993 [14.0][MIG] sale_timesheet
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_timesheet/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_timesheet/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_timesheet/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3040 [MIG][14.0] account_edi: Migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account_edi/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3045 [MIG][14.0] association: nothing to do
  docsource/modules130-140.rst
Labels: bot is merging ⏳

#3046 [14.0][MIG] account_edi_facturx: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account_edi_facturx/14.0.1.0/upgrade_analysis_work.txt
Labels: approved

#3051 [MIG][14.0] crm_iap_lead: Migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/crm_iap_lead/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/crm_iap_lead/14.0.1.1/upgrade_analysis_work.txt
Labels: approved

#3012 [13.0][IMP] OpenUpgrade: log sql_constraints in analysis
  odoo/addons/base/models/ir_model.py
  odoo/addons/openupgrade_records/lib/compare.py
  odoo/addons/openupgrade_records/models/generate_records_wizard.py
  odoo/addons/openupgrade_records/models/openupgrade_record.py
  odoo/openupgrade/openupgrade_log.py
Labels: needs review

#3059 [14.0][FIX] account auto link statement with move
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review

#3070 [14.0][FIX] account: auto link payment with move
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review, approved

#3083 [12.0][ADD] apriori: account_analytic_asset -> account_asset_management
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review, approved

#3044 [MIG][14.0] account_check_printing: Migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account_check_printing/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/account_check_printing/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/account_check_printing/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3085 [14.0][FIX] crm: correct call of delete_records_safely_by_xml_id
  openupgrade_scripts/scripts/crm/14.0.1.2/post-migration.py
Labels: needs review

#3089 [13.0][OU-FIX] product: migrate pricelist settings
  addons/product/migrations/13.0.1.2/post-migration.py
Labels: needs review

#3095 [14.0][FIX] account: make use of enumerate
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: needs review

#3097 [14.0][FIX] account: make unfold_manual_account_groups fail-safe
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: needs review

#3110 [MIG][14.0]pos_restaurant_adyen: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/pos_restaurant_adyen/14.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳

#3111 [12.0][OU-FIX] repair: correct xmlid renames
  addons/repair/migrations/12.0.1.0/pre-migration.py
Labels: needs review, approved

#2977 [14.0][FIX] base: assure module category parents are correct
  openupgrade_scripts/scripts/base/14.0.1.3/post-migrate.py
  openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py
Labels: needs review

#3011 [13.0][FIX] product: move product_variant_combination logic from post to pre-migration
  addons/product/migrations/13.0.1.2/openupgrade_analysis_work.txt
  addons/product/migrations/13.0.1.2/post-migration.py
  addons/product/migrations/13.0.1.2/pre-migration.py
Labels: needs review

#3118 [12.0][FIX] stock: avoid duplicated putaway strategies
  addons/stock/migrations/12.0.1.1/post-migration.py
Labels: needs review
