Repository OCA/OpenUpgrade, pull requests merged in 2022-08, with the labels that each got.

#3015 [13.0] stock_account: link account moves to svl
  addons/stock_account/migrations/13.0.1.1/post-migration.py
Labels: needs review, approved

#3502 [15.0][MIG] crm: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/crm/15.0.1.6/post-migration.py
  openupgrade_scripts/scripts/crm/15.0.1.6/pre-migration.py
  openupgrade_scripts/scripts/crm/15.0.1.6/upgrade_analysis_work.txt
Labels: needs review

#3503 [15.0][MIG] iap_crm: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/iap_crm/15.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3504 [15.0][FIX] crm: avoid deleting mail alias record
  openupgrade_scripts/scripts/crm/15.0.1.6/post-migration.py
  openupgrade_scripts/scripts/crm/15.0.1.6/upgrade_analysis_work.txt
Labels: needs review

#3491 [15.0][MIG] project: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/project/15.0.1.2/post-migration.py
  openupgrade_scripts/scripts/project/15.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/project/15.0.1.2/upgrade_analysis_work.txt
Labels: needs review

#3499 [14.0][MIG] point_of_sale: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/point_of_sale/14.0.1.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/point_of_sale/14.0.1.0.1/post-migration.py
  openupgrade_scripts/scripts/point_of_sale/14.0.1.0.1/pre-migration.py
  openupgrade_scripts/scripts/point_of_sale/14.0.1.0.1/upgrade_analysis_work.txt
Labels: needs review

#3512 [15.0][OU-ADD] project_mail_chatter: Merged project_mail_chatter to project.
  openupgrade_scripts/apriori.py
Labels: approved

#3506 [14.0][FIX] account: take payment_ref only if move_name is NULL (or '')
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review

#3517 [15.0][FIX] project: insert boolean correctly in addd_fields method
  openupgrade_scripts/scripts/project/15.0.1.2/pre-migration.py
Labels: needs review

#3522 [15.0][MIG] crm_sms
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/crm_sms/15.0.1.1/upgrade_analysis_work.txt
Labels: Nothing to do

#3523 [14.0][FIX] documentation: Prefix merged/renamed modules with `Done`
  docsource/modules130-140.rst
Labels: needs review

#3526 [14.0][MIG] project_timesheet_holidays: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/project_timesheet_holidays/14.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3528 [MIG][14.0] website_sale_management: Nothing to do
  docsource/modules130-140.rst
Labels: Nothing to do

#2882 [14.0][MIG] pos_sale
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/pos_sale/14.0.1.0/openupgrade_analysis_work.txt
  openupgrade_scripts/scripts/pos_sale/14.0.1.0/pre-migration.py
Labels: needs review, approved

#3529 [MIG][14.0] mass_mailing_sale: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/mass_mailing_sale/14.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#3530 [MIG][14.0] website_sale_comparison: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_sale_comparison/14.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#2875 [14.0][MIG] purchase_requisition
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/purchase_requisition/14.0.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/purchase_requisition/14.0.0.1/upgrade_analysis_work.txt
Labels: needs review, approved, Nothing to do

#3538 [14.0][MIG] web_confirm_duplicate -> web_copy_confirm
  openupgrade_scripts/apriori.py
Labels: approved

#3537 [13.0][OU-IMP] point_of_sale: stock_location_id
  addons/point_of_sale/migrations/13.0.1.0.1/openupgrade_analysis_work.txt
  addons/point_of_sale/migrations/13.0.1.0.1/post-migration.py
Labels: approved

#3041 [MIG][14.0] account_edi_extended: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/account_edi_extended/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3543 [15.0][FIX] hr: load noupdate data
  openupgrade_scripts/scripts/hr/15.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/hr/15.0.1.1/post-migration.py
Labels: needs review
