Repository OCA/OpenUpgrade, pull requests merged in 2022-05, with the labels that each got.

#3023 [14.0][OU-ADD] procurement_jit: Nothing to do
  docsource/modules130-140.rst
Labels: Blocked by dependency, bot is merging ⏳, Nothing to do

#3226 [14.0][FIX] account: correct move's currency
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review

#3239 [13.0][FIX] stock: putaway rules in multi-company
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: needs review, approved

#3140 [FIX][14.0] account: process account payment transfer
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#3159 [FIX][14.0] account: duplicate journal items when filling account payment / statement line with no move
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: needs review, approved, ready to merge

#3249 [13.0][OU] base: fix translation term states
  odoo/addons/base/migrations/13.0.1.3/end-migration.py
Labels: approved

#3250 [13.0][FIX] calendar: error in pre-migration due to white spaces
  addons/calendar/migrations/13.0.1.0/pre-migration.py
Labels: approved

#3241 [13.0][FIX] mrp, repair: map locations
  addons/mrp/migrations/13.0.2.0/post-migration.py
  addons/repair/migrations/13.0.1.0/post-migration.py
  addons/stock/migrations/13.0.1.1/end-migration.py
  addons/stock/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/stock/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3251 [OUFIX][14.0]account : no liquidity line created for bank statement line
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
Labels: needs review, approved

#3247 [13.0][FIX] web_editor: remove deleting noupdate=0 xml records
  addons/web_editor/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/web_editor/migrations/13.0.1.0/post-migration.py
Labels: approved, ready to merge

#3255 [FIX] add hr_gamification in the coverage file
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review, Nothing to do

#3223 [14.0][FIX] account: avoid duplicating account groups
  openupgrade_scripts/scripts/account/14.0.1.1/end-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#3161 [12.0][FIX] base,sale_management: rename module in rename_models
  addons/sale_management/migrations/12.0.1.0/pre-migration.py
  odoo/addons/base/migrations/12.0.1.3/pre-migration.py
Labels: needs review

#2671 [13.0][FIX] mass_mailing: fill campaign_id in some models
  addons/mass_mailing/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/13.0.2.0/post-migration.py
  addons/mass_mailing/migrations/13.0.2.0/pre-migration.py
Labels: needs review

#3258 [13.0][OU-FIX] mass_mailing: prevent deleting mailing list
  addons/mass_mailing/migrations/13.0.2.0/openupgrade_analysis_work.txt
  addons/mass_mailing/migrations/13.0.2.0/post-migration.py
  addons/mass_mailing/migrations/13.0.2.0/pre-migration.py
Labels: approved

#3257 [13.0][OU-FIX] pos_sale: map old pos.order to crm_team_id
  addons/pos_sale/migrations/13.0.1.0/openupgrade_analysis_work.txt
  addons/pos_sale/migrations/13.0.1.0/post-migration.py
Labels: approved
