Repository OCA/OpenUpgrade, pull requests merged in 2022-09, with the labels that each got.

#3477 [14.0][FIX] openupgrade_framework: Proper module dependency resolution
  openupgrade_framework/odoo_patch/odoo/modules/graph.py
Labels: approved, ready to merge

#3549 [14.0][OU-ADD] website_twitter: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/website_twitter/14.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3550 [14.0][OU-ADD] payment_stripe: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/payment_stripe/14.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3547 [15.0][FIX] openupgrade_framework: Proper module dependency resolution
  openupgrade_framework/odoo_patch/odoo/modules/graph.py
Labels: approved, ready to merge

#3558 [14.0][FIX] crm: assure deprecated table doesn't give problems
  openupgrade_scripts/scripts/crm/14.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/crm/14.0.1.2/upgrade_analysis_work.txt
Labels: needs review

#3560 [15.0][FIX] framework: monkeypatch needs to patch original method
  openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
Labels: needs review

#3562 [15.0][FIX] framework: monkeypatch needs to patch original method (fixup)
  openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
Labels: needs review

#3563 [13.0][IMP] apriori: account_invoice_repair_link -> repair
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review

#3556 [15.0][FIX] apriori: merge instead of rename l10n_eu_service
  openupgrade_scripts/apriori.py
Labels: needs review

#3557 [15.0][FIX] mail: assure unicity in mail.channel.partner
  openupgrade_scripts/scripts/mail/15.0.1.5/pre-migration.py
Labels: needs review

#1614 [10.0][FIX] fix fill_stock_move_unit_factor perf and use openupgrade.logged…
  addons/mrp/migrations/10.0.2.0/post-migration.py
Labels: work in progress, approved

#3575 [14.0][FIX] project: complete project visibility when 'followers' option
  openupgrade_scripts/scripts/project/14.0.1.1/post-migration.py
Labels: needs review

#3577 [14.0][FIX] account: Only fill account.move>payment_id when account.payment>move_id is set
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review
