Repository OCA/OpenUpgrade, pull requests merged in 2022-03, with the labels that each got.

#3163 [11.0] update upstream 43200e9dcc1
  addons/web_editor/controllers/main.py
  odoo/tools/mimetypes.py
Labels: needs review

#3164 [12.0] update upstream 720e2daafa9
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/payment_stripe_sca/controllers/main.py
  addons/web_editor/controllers/main.py
  doc/cla/individual/petrus-v.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/mimetypes.py
Labels: needs review

#3169 [14.0][IMP] account: avoid repeating code
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review

#3170 [13.0][FIX] l10n_es: parent taxes should be of l10n_es module
  addons/l10n_es/migrations/13.0.4.0/post-migration.py
Labels: needs review

#3139 [13.0][MIG] sale_product_classification: Renamed to product_abc_classification_sale
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review, approved

#3174 [12.0][MIG] web_tree_image: Rename to web_tree_image_tooltip
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#3172 [FIX][14.0] hr_holidays: missing Time Off Description
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/14.0.1.5/upgrade_analysis_work.txt
Labels: approved

#2973 [13.0][IMP] account: avoid loop, do all in one query
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3181 [FIX][14.0]rating: fix update rating value
  openupgrade_scripts/scripts/rating/14.0.1.0/pre-migration.py
Labels: needs review

#3183 [13.0][FIX] account: Added extra queries to migrate tags from non-invoice move lines wherever possible.
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3190 [13.0][FIX] l10n_es: parent taxes should not be manually added ones (fixup)
  addons/l10n_es/migrations/13.0.4.0/post-migration.py
Labels: needs review

#3192 [14.0][IMP] account: speed up some queries
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
Labels: needs review

#2815 [14.0][MIG] maintenance
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/maintenance/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/maintenance/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/maintenance/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/maintenance/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#2859 [14.0][MIG] fleet
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/fleet/14.0.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/fleet/14.0.0.1/post-migration.py
  openupgrade_scripts/scripts/fleet/14.0.0.1/pre-migration.py
  openupgrade_scripts/scripts/fleet/14.0.0.1/upgrade_analysis_work.txt
Labels: needs review, approved

#2863 [14.0][MIG] hr_maintenance
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_maintenance/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2873 [14.0][MIG] hr_expense
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/hr_expense/14.0.2.0/openupgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3096 [MIG][14.0]sale_margin: migration script
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_margin/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_margin/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved

#2788 [14.0][MIG] stock
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/stock/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/stock/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review, approved

#2997 [14.0][OU-ADD] repair: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/repair/14.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/repair/14.0.1.0/post-migration.py
  openupgrade_scripts/scripts/repair/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/repair/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved

#2841 [14.0][OU-ADD] stock_account: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/stock_account/14.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/stock_account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock_account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock_account/14.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#2844 [14.0][OU-ADD] purchase: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/purchase/14.0.1.2/noupdate_changes.xml
  openupgrade_scripts/scripts/purchase/14.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase/14.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/purchase/14.0.1.2/upgrade_analysis_work.txt
Labels: needs review

#2853 [14.0][OU-ADD] mrp: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/mrp/14.0.2.0/noupdate_changes.xml
  openupgrade_scripts/scripts/mrp/14.0.2.0/post-migration.py
  openupgrade_scripts/scripts/mrp/14.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/mrp/14.0.2.0/upgrade_analysis_work.txt
Labels: needs review

#2876 [14.0][OU-ADD] purchase_mrp: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/purchase_mrp/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2874 [14.0][OU-ADD] purchase_stock: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/purchase_stock/14.0.1.2/upgrade_analysis_work.txt
Labels: needs review, approved, Nothing to do

#2831 [14.0][OU-ADD] membership: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/membership/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#2805 [14.0][OU-ADD] account_payment: Nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3062 [14.0][OU-ADD] event_sale: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/event_sale/14.0.1.2/noupdate_changes.xml
  openupgrade_scripts/scripts/event_sale/14.0.1.2/post-migration.py
  openupgrade_scripts/scripts/event_sale/14.0.1.2/upgrade_analysis_work.txt
Labels: needs review, approved

#3047 [14.0][OU-ADD] auth_password_policy: Nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3048 [14.0][OU-ADD] auth_password_policy_signup: Nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#2842 [14.0][OU-ADD] mass_mailing: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/mass_mailing/14.0.2.2/pre-migration.py
  openupgrade_scripts/scripts/mass_mailing/14.0.2.2/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3077 [14.0][OU-ADD] mass_mailing_event: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3079 [MIG][14.0] mass_mailing_event_track: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3078 [14.0][OU-ADD] mass_mailing_event_sms: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#3080 [14.0][OU-ADD] mass_mailing_event_track_sms: nothing to do
  docsource/modules130-140.rst
Labels: needs review, Nothing to do

#2862 [14.0][OU-ADD] sale_stock: Migration scripts
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_stock/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_stock/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3202 [14.0][OU-ADD] sale_mrp: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/sale_mrp/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3191 [14.0][FIX] base: assure existing users can export
  openupgrade_scripts/scripts/base/14.0.1.3/post-migrate.py
  openupgrade_scripts/scripts/base/14.0.1.3/upgrade_analysis_work.txt
Labels: needs review
