Repository OCA/OpenUpgrade, pull requests merged in 2023-02, with the labels that each got.

#3182 [FIX][14.0] calendar: fix duplicated events
  openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py
Labels: needs review, approved

#3713 [13.0][FIX] account: Transfer invoice line description to matched journal items
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review

#3719 [14][IMP] apriori:sale_order_pricelist_tracking to sale
  openupgrade_scripts/apriori.py
Labels: approved, bot is merging ⏳

#3391 [MIG][15.0] product_margin: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/product_margin/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3667 [15.0][MIG] website_sale_cart_no_redirect: Migration to 15.0
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge

#3654 [15.0][OU-ADD] purchase_invoicing_no_zero_line: Merged into purchase
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge

#3729 [OU] hr_leave_custom_hour_interval: renamed module
  openupgrade_scripts/apriori.py
Labels: Waiting

#3726 [11.0][FIX] hr_timesheet: Migrate the users of the timesheets' old "Officer" group to the new "Manager" group.
  addons/hr_timesheet/migrations/11.0.1.0/post-migration.py
  addons/hr_timesheet/migrations/11.0.1.0/pre-migration.py
Labels: needs review, bot is merging ⏳

#3385 [MIG][15.0] gamification_sale_crm: nothing to do
  docsource/modules140-150.rst
Labels: needs review, approved

#3736 [15.0][MIG] crm_livechat
  docsource/modules140-150.rst
Labels: Nothing to do

#3737 [15.0][MIG] mass_mailing_event
  docsource/modules140-150.rst
Labels: Nothing to do

#3439 [MIG][15.0] snailmail_account: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/snailmail_account/15.0.0.1/upgrade_analysis_work.txt
Labels: Nothing to do

#3738 [15.0][MIG] website_event
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_event/15.0.1.4/post-migration.py
  openupgrade_scripts/scripts/website_event/15.0.1.4/pre-migration.py
  openupgrade_scripts/scripts/website_event/15.0.1.4/upgrade_analysis_work.txt
Labels: needs review

#3739 [15.0][MIG] website_hr_recruitment
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_hr_recruitment/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3309 [MIG][15.0] website_slides: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_slides/15.0.2.4/post-migration.py
  openupgrade_scripts/scripts/website_slides/15.0.2.4/pre-migration.py
  openupgrade_scripts/scripts/website_slides/15.0.2.4/upgrade_analysis_work.txt
Labels: needs review, approved

#3740 [15.0][MIG] website_event_sale
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_event_sale/15.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/website_slides/15.0.2.4/pre-migration.py
Labels: needs review, Nothing to do

#3741 [15.0][MIG] website_sms
  docsource/modules140-150.rst
Labels: Nothing to do

#3742 [15.0][MIG] website_sale_management
  docsource/modules140-150.rst
Labels: needs review

#3434 [MIG][15.0] sale_expense: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/sale_expense/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Nothing to do
