Repository OCA/OpenUpgrade, pull requests merged in 2023-12, with the labels that each got.

#4242 [15.0][OU-ADD] website_crm: Migrate website_crm views
  openupgrade_scripts/scripts/website_crm/15.0.2.1/post-migration.py
Labels: approved

#4218 [MIG] l10n_it_ricevute_bancarie: Rename to l10n_it_riba
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge

#4261 [15.0][OU-ADD] project_category: Renamed into project_type
  openupgrade_scripts/apriori.py
Labels: approved

#4227 [DOC] Describe how to propose a migration script to the community.
  docsource/090_contribute.rst
Labels: approved, ready to merge, bot is merging ⏳

#4262 [15.0][MIG] sale_project_service_tracking_copy_tasks -> sale_project_copy_tasks
  openupgrade_scripts/apriori.py
Labels: approved

#4271 [15.0][OU-FIX] don't fail when there's an unknown field in a view
  openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
Labels: approved

#4167 [15.0] [OU-ADD] digest
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/digest/15.0.1.1/post-migration.py
Labels: approved, ready to merge
