Repository OCA/OpenUpgrade, pull requests merged in 2023-11, with the labels that each got.

#4199 [16.0][IMP] apriori: coupon_commercial_partner_applicability merged into loyalty_partner_applicability
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/base/16.0.1.3/pre-migration.py
Labels: approved

#4103 Documentation - refactor of the structure
  .gitignore
  build_openupgrade_docs
  docsource/010_introduction.rst
  docsource/020_required_knowledge.rst
  docsource/030_coverage_analysis.rst
  docsource/040_run_migration.rst
  docsource/050_after_migration.rst
  docsource/060_odoo_migration_manager.rst
  docsource/070_migration_files.rst
  docsource/080_migration_script_development.rst
  docsource/090_contribute.rst
  docsource/analyse.rst
  docsource/analysis.rst
  docsource/coverage_analysis/coverage_legend.rst
  docsource/coverage_analysis/images/deleted.png
  docsource/coverage_analysis/images/new.png
  docsource/devfaq.rst
  docsource/index.rst
  docsource/migrating_database.rst
  docsource/status.rst
  docsource/use_cases/value_mapping.rst
  docsource/xmlids.rst
Labels: bot is merging ⏳

#4023 [16.0][OU-ADD] website_partner: Nothing to do
  docsource/modules150-160.rst
Labels: approved, bot is merging ⏳, Dependency OK

#4217 [ADD] documentation - required knowledge
  docsource/020_required_knowledge.rst
Labels: approved

#4179 [16.0][OU-ADD] payment_paypal: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/payment_paypal/16.0.2.0/noupdate_changes.xml
  openupgrade_scripts/scripts/payment_paypal/16.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_paypal/16.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/payment_paypal/16.0.2.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4178 [16.0][OU-ADD] payment_stripe: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/payment_stripe/16.0.2.0/noupdate_changes.xml
  openupgrade_scripts/scripts/payment_stripe/16.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_stripe/16.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/payment_stripe/16.0.2.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4246 [16.0][OU-ADD] apriori: coupon_criteria_multi_product renamed to loyalty_criteria_multi_product
  openupgrade_scripts/apriori.py
Labels: approved
