Repository OCA/OpenUpgrade, pull requests merged in 2023-03, with the labels that each got.

#3747 [13.0] update upstream fc468f5a1a7
  addons/auth_oauth/migrations/13.0.1.0/noupdate_changes.xml
  addons/auth_oauth/migrations/13.0.1.0/post-migration.py
  addons/base_iban/models/res_partner_bank.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/website_slides/static/src/js/slides_upload.js
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3336 [MIG][15.0] hr_holidays: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_holidays/15.0.1.5/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_holidays/15.0.1.5/post-migration.py
  openupgrade_scripts/scripts/hr_holidays/15.0.1.5/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/15.0.1.5/upgrade_analysis_work.txt
Labels: needs review

#3313 [MIG][15.0] hr_holidays_attendance: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_holidays_attendance/15.0.1.0/upgrade_analysis_work.txt
Labels: Blocked by dependency, bot is merging ⏳, Nothing to do

#3510 [15.0][MIG] stock: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/stock/15.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/15.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/15.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#3527 [15.0][MIG] stock_account: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/stock_account/15.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock_account/15.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock_account/15.0.1.1/upgrade_analysis_work.txt
Labels: needs review, Blocked by dependency, bot is merging ⏳

#3321 [MIG][15.0]purchase_requisition_stock: add mig script v15
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/purchase_requisition_stock/15.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase_requisition_stock/15.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3335 [MIG][15.0]purchase_stock: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/purchase_stock/15.0.1.2/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Nothing to do

#3390 [MIG][15.0] product_matrix: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/product_matrix/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3633 [15.0][OU] product_expiry: Migration script to 15.0
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/product_expiry/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3431 [MIG][15.0] procurement_jit: nothing to do
  docsource/modules140-150.rst
Labels: Blocked by dependency, bot is merging ⏳, Nothing to do

#3393 [MIG][15.0] sale_product_matrix: migration for 15.0, nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/sale_product_matrix/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3441 [MIG][15.0] stock_landed_costs: nothing to do
  docsource/modules140-150.rst
Labels: bot is merging ⏳

#3442 [MIG][15.0] stock_sms: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/stock_sms/15.0.1.0/post-migration.py
Labels: needs review, bot is merging ⏳

#3338 [MIG][15.0] website_slides_survey: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_slides_survey/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_slides_survey/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3308 [MIG][15.0] website_slides_forum: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_slides_forum/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3641 [15.0][IMP] apriori: stock_inventory_valuation_pivot to stock_account
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge

#3531 [15.0][MIG] sale_stock: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/sale_stock/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_stock/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_stock/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3652 [15.0][OU-ADD] stock_picking_batch: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/stock_picking_batch/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, bot is merging ⏳

#3432 [MIG][15.0] project_timesheet_holidays: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/project_timesheet_holidays/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/project_timesheet_holidays/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge

#3725 [15.0][MIG] website_sale_stock: Migration scripts to v15
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_sale_stock/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_sale_stock/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_sale_stock/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳

#3750 [11.0][OU-FIX] hr_timesheet: Don't insert same permission several times
  addons/hr_timesheet/migrations/11.0.1.0/post-migration.py
Labels: needs review, approved, bot is merging ⏳

#3647 [15.0][OU-ADD] website_sale_delivery: Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_sale_delivery/15.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#3382 [MIG][15.0] crm_iap_lead_website: nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website_crm_iap_reveal/15.0.1.1/upgrade_analysis_work.txt
Labels: approved

#3413 [MIG][15.0] hr_presence: migration script
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/hr_presence/15.0.1.0/post-migration.py
Labels: bot is merging ⏳

#3326 [ADD] pos_restaurant migration
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/pos_restaurant/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Nothing to do

#3758 [15.0][FIX] sale_coupon: handle noupdate changes in template
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/sale_coupon/15.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/sale_coupon/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_coupon/15.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3761 [13.0][IMP] OCA module product_pricelist_margin renamed into product_pricelist_simulation
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: needs review, approved, bot is merging ⏳

#3763 [16.0][FIX] Switch Flake8 pre-commit source to GitHub
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#3766 [9.0][FIX] hr: delete safely constraint
  addons/account/migrations/9.0.1.1/post-migration.py
  addons/hr/migrations/9.0.1.1/pre-migration.py
Labels: needs review

#3760 [ADD] marked account_balance_line as merged in Odoo core. (account)
  openupgrade_scripts/apriori.py
Labels: needs review

#3785 [14.0][FIX] hr_expense: update noupdate data in case data exists
  openupgrade_scripts/scripts/hr_expense/14.0.2.0/post-migration.py
Labels: needs review

#3699 [15.0][ADD] hr_expense: disable reconcile and fiscalyear check during migration
  openupgrade_scripts/scripts/hr_expense/15.0.2.0/post-migration.py
Labels: needs review, approved, ready to merge

#3744 [15.0][MIG] mrp
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/mrp/15.0.2.0/post-migration.py
  openupgrade_scripts/scripts/mrp/15.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/mrp/15.0.2.0/upgrade_analysis_work.txt
Labels: needs review, approved

#3787 [15.0][MIG] sale_mrp: Migration to version 15.0
  docsource/modules140-150.rst
Labels: bot is merging ⏳

#3794 [15.0][OU-ADD] website_sale_attribute_filter_price: Price filter added to website_sale
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website_sale/15.0.1.1/pre-migration.py
Labels: approved

#3535 [14.0][OU-ADD] website_snippet_carousel_product: Merged to website_sale
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website_sale/14.0.1.0/post-migration-website_snippet_carousel_product.py
Labels: needs review, Waiting

#3762 [16.0][REF] product_form_purchase_link merged into purchase module
  openupgrade_scripts/apriori.py
Labels: needs review, approved

#3300 [14.0][OU-ADD] l10n_fr: Nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/l10n_fr/14.0.2.0/upgrade_analysis_work.txt
Labels: needs review

#3805 [14.0][FIX] account: update noupdate_changes.xml
  openupgrade_scripts/scripts/account/14.0.1.1/noupdate_changes.xml
Labels: needs review, approved, bot is merging ⏳

#3626 [14.0][OU-IMP] account: Compute stored function fields by SQL
  openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3173 [13.0][FIX] account: make us of merge_models openupgradelib method
  addons/account/migrations/13.0.1.1/post-migration.py
Labels: needs review
