Repository OCA/OpenUpgrade, pull requests merged in 2023-06, with the labels that each got.

#3895 [15.0][OU-FIX] website: website update website form call
  openupgrade_scripts/scripts/website/15.0.1.0/post-migration.py
Labels: approved

#3905 [15.0][OU-ADD] sale_coupon_portal_commercial_partner_applicability: Renamed to coupon_portal_commercial_partner_applicability
  openupgrade_scripts/apriori.py
Labels: approved, Blocked by dependency

#3832 [16.0] [OU-ADD] mail
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/mail/16.0.1.10/noupdate_changes.xml
  openupgrade_scripts/scripts/mail/16.0.1.10/post-migration.py
  openupgrade_scripts/scripts/mail/16.0.1.10/pre-migration.py
  openupgrade_scripts/scripts/mail/16.0.1.10/tests/data.py
  openupgrade_scripts/scripts/mail/16.0.1.10/tests/test_mail_migration.py
  openupgrade_scripts/scripts/mail/16.0.1.10/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3897 [16.0][OU-ADD] contacts: Nothing to do
  docsource/modules150-160.rst
Labels: Blocked by dependency, bot is merging ⏳

#3898 [16.0][OU-ADD] rating: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/rating/16.0.1.1/upgrade_analysis_work.txt
Labels: Blocked by dependency, bot is merging ⏳

#3864 [ADD] Use Case : noupdate_xml_change
  docsource/development.rst
  docsource/use_cases/noupdate_xml_entry_changed.rst
Labels: approved

#3901 [DOC-ADD] Use Case : Model renaming
  docsource/development.rst
  docsource/use_cases/model_renaming.rst
Labels: approved, bot is merging ⏳

#3873 [DOC] Use case : field fast precomputation
  docsource/development.rst
  docsource/use_cases/field_fast_precomputation.rst
Labels: approved, ready to merge, bot is merging ⏳

#3880 [16.0][OU-ADD] product
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/product/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/product/16.0.1.2/upgrade_analysis_work.txt
Labels: approved, ready to merge, bot is merging ⏳

#3930 [16.0][OU-ADD] barcodes: Nothing to do
  docsource/modules150-160.rst
Labels: approved, bot is merging ⏳

#3959 [14.0][OU-IMP] website: convert all HTML fields from version 13 to 14
  openupgrade_scripts/scripts/website/14.0.1.0/end-migration.py
Labels: approved
