Repository OCA/OpenUpgrade, pull requests merged in 2023-09, with the labels that each got.

#4125 [14.0][OU-IMP] website: refine html migration exlusions
  openupgrade_scripts/scripts/website/14.0.1.0/end-migration.py
Labels: approved

#4129 [15.0][FIX] stock: Incoming moves visibility window
  openupgrade_scripts/scripts/stock/15.0.1.1/post-migration.py
Labels: approved

#4128 [16.0][FIX] base: case translation when no model data
  openupgrade_scripts/scripts/base/16.0.1.3/pre-migration.py
Labels: needs review

#4127 [16.0] Fix openupgradelib dependencies
  .pre-commit-config.yaml
  oca_dependencies.txt
  requirements.txt
  setup/openupgrade_framework/setup.py
  setup/openupgrade_scripts/setup.py
Labels: needs review, approved

#4132 [13.0] update upstream 483cc20b95e
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: needs review

#2726 [13.0][MIG] l10n_ch
  addons/l10n_ch/migrations/13.0.10.0/noupdate_changes.xml
  addons/l10n_ch/migrations/13.0.11.0/noupdate_changes.xml
  addons/l10n_ch/migrations/13.0.11.0/openupgrade_analysis_work.txt
  addons/l10n_ch/migrations/13.0.11.0/post-migration.py
  addons/l10n_ch/migrations/13.0.11.0/pre-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: needs review

#3811 [16.0][OU-ADD] stock_picking_backorder_strategy: Merged into stock
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge, bot is merging ⏳
