Repository OCA/OpenUpgrade, pull requests merged in 2023-05, with the labels that each got.

#3838 [ADD] Missing API references, for specific methods for openupgrade 12.0, 13.0 and 16.0
  docsource/API.rst
Labels: approved

#3841 [REF] Switch to sphinx_rtd_theme
  .github/workflows/documentation-commit.yml
  .github/workflows/documentation.yml
  docsource/conf.py
Labels: approved, bot is merging ⏳

#3843 [15.0][OU-ADD] website_blog: update blog_blog cover properties field
  openupgrade_scripts/scripts/website_blog/14.0.1.0/post-migration.py
Labels: approved

#3328 [MIG][14.0] l10n_fr_fec (nothing to do)
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/l10n_fr_fec/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Blocked by dependency, bot is merging ⏳, Nothing to do

#3848 [11.0][OU-IMP] sale: Auto-create icp from old deposit_product_id_setting field (v10) to new default_deposit_product_id field (v11)
  addons/sale/migrations/11.0.1.1/post-migration.py
Labels: approved

#3844 [DOC-ADD] Use Case : XML_ID renaming
  docsource/development.rst
  docsource/use_cases/xml_id_renaming.rst
Labels: approved

#3840 [REF] Refactor files that describes the branch.
  .github/workflows/documentation-commit.yml
  .github/workflows/documentation.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  README.rst
  build_openupgrade_docs
  requirements.txt
Labels: bot is merging ⏳

#3861 [14.0][OU-ADD] apriori: website_sale_product_style_badge merged into website_sale
  openupgrade_scripts/apriori.py
Labels: approved

#3865 [14.0][OU-IMP] sale_margin: recompute existing margin_percent
  openupgrade_scripts/scripts/sale_margin/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_margin/14.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#3863 [REF] Remove openupgradelib API from the OpenUpgrade documentation
  .github/workflows/documentation-commit.yml
  .github/workflows/documentation.yml
  README.rst
  build_openupgrade_docs
  docsource/API.rst
  docsource/development.rst
  docsource/index.rst
  requirements.txt
Labels: Blocked by dependency

#3769 [16.0][MIG] base_address_extended
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/base_address_extended/16.0.1.1/upgrade_analysis_work.txt
Labels: approved

#3845 [DOC-ADD] Use Case : mapping values
  docsource/development.rst
  docsource/use_cases/images/value-mapping-error.png
  docsource/use_cases/value_mapping.rst
Labels: approved

#3883 [14.0][MIG] apriori: hr_period -> hr_payroll_period
  openupgrade_scripts/apriori.py
Labels: approved
