Repository OCA/OpenUpgrade, pull requests merged in 2024-04, with the labels that each got.

#4182 [16.0][OU-ADD] website_sale_stock: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_stock/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge, Dependency OK

#4136 [16.0][OU-ADD] product_expiry: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/product_expiry/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4135 [16.0][OU-ADD] stock_dropshipping: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/stock_dropshipping/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4183 [16.0][OU-ADD] website_sale_delivery: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_delivery/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4375 [14.0][IMP] base: vacuum of transient models (forward port)
  openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py
  openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py
Labels: approved

#4348 [15.0][OU-ADD] website_event_crm: Nothing to do
  docsource/modules140-150.rst
Labels: bot is merging ⏳, Dependency OK

#4347 [16.0][OU-ADD] website_event_crm: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Dependency OK

#4157 [16.0][OU-ADD] mrp_account: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/mrp_account/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4116 [16.0][OU-ADD] sale_mrp: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_mrp/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4170 [16.0][OU-ADD] hr_work_entry: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_work_entry/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4155 [16.0][OU-ADD] purchase_mrp: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/purchase_mrp/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#3970 [16.0][OU-ADD] stock_sms: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/stock_sms/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4077 [16.0][OU-ADD] sale_stock_margin: nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Dependency OK

#4031 [16.0][OU-ADD] sale_project_stock: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Dependency OK

#4086 [16.0] [OU-ADD] website_event_track
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_event_track/16.0.1.3/post-migration.py
  openupgrade_scripts/scripts/website_event_track/16.0.1.3/upgrade_analysis_work.txt
Labels: Dependency OK

#4087 [16.0] [OU-ADD] website_forum: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_forum/16.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4392 [16.0][OU-ADD] point_of_sale
  openupgrade_scripts/scripts/point_of_sale/16.0.1.0.1/post-migration.py
  openupgrade_scripts/scripts/point_of_sale/16.0.1.0.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4267 [OU-ADD] pos_sale module
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/pos_sale/15.0.1.1/post-migration.py
  openupgrade_scripts/scripts/pos_sale/15.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4268 [16.0][OU-ADD] pos_restaurant: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/pos_restaurant/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4269 [16.0][OU-ADD] pos_sale module
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/pos_sale/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/pos_sale/16.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK
