Repository OCA/OpenUpgrade, pull requests merged in 2024-10, with the labels that each got.

#4325 [16.0][OU-ADD] purchase_picking_state: Merged into purchase_stock
  openupgrade_scripts/apriori.py
Labels: approved

#4594 Update __manifest__.py - fixed a typo
  openupgrade_scripts/__manifest__.py
Labels: bot is merging ⏳

#4612 [17.0][OU-ADD] base_setup: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4611 [17.0][OU-ADD] base_import: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/base_import/17.0.2.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK

#4600 [17.0][OU-ADD] mail: migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/mail/17.0.1.15/noupdate_changes.xml
  openupgrade_scripts/scripts/mail/17.0.1.15/post-migration.py
  openupgrade_scripts/scripts/mail/17.0.1.15/pre-migration.py
  openupgrade_scripts/scripts/mail/17.0.1.15/upgrade_analysis_work.txt
Labels: Blocked by dependency

#4603 [17.0][OU-ADD] contacts: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4635 [17.0][OU-ADD] auth_totp. Nothing to do
  docsource/modules160-170.rst
Labels: Dependency OK

#4638 [17.0][OU-ADD] web_editor
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/web_editor/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4624 [17.0][OU-ADD] web_unsplash : Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4640 [OU-ADD] uom. Nothing to do.
  docsource/modules160-170.rst
Labels: bot is merging ⏳

#4626 [17.0][OU-ADD] http_routing: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4627 [17.0][OU-ADD] phone_validation: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/phone_validation/17.0.2.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4643 [17.0][OU-ADD] rating: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/rating/17.0.1.1/upgrade_analysis_work.txt
Labels: approved

#4465 [17.0][OU-ADD] onboarding: migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/onboarding/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/onboarding/17.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/onboarding/17.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK
