Repository OCA/OpenUpgrade, pull requests merged in 2024-11, with the labels that each got.

#4487 [17.0][OU-ADD] auth_signup: migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/auth_signup/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/auth_signup/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4467 [17.0][OU-ADD] portal: migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/portal/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/portal/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4609 [17.0][OU-ADD] auth_totp_portal: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4460 [17.0][OU-ADD] calendar: migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/calendar/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/calendar/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4032 [16.0][OU-ADD] sale_expense_margin: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Dependency OK

#4471 [17.0][OU-ADD] resource: migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/resource/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/resource/17.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/resource/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4642 [17.0][OU-ADD] digest: migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/digest/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/digest/17.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/digest/17.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4598 [17.0][OU-ADD] product: migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/product/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/product/17.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/product/17.0.1.2/upgrade_analysis_work.txt
Labels: Dependency OK

#4475 [16.0][IMP] stock: pre-compute quantity_done
  openupgrade_scripts/scripts/stock/16.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/16.0.1.1/upgrade_analysis_work.txt
Labels: approved

#4660 [17.0][OU-ADD] web_pwa_oca: Merged into web
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/web/17.0.1.0/pre-migration.py
Labels: approved

#4669 [17.0][OU-ADD] enable tests, add decorator to make them convenient to use
  .github/workflows/documentation-commit.yml
  .github/workflows/test.yml
  openupgrade_framework/__init__.py
Labels: needs review

#4675 [17.0][OU-ADD] apriori: website_event_questions to website_event
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
Labels: approved

#4661 [15.0][OU-ADD] l10n_es_extra_data: Merged into l10n_es
  openupgrade_scripts/apriori.py
Labels: approved
