Repository OCA/OpenUpgrade, pull requests merged in 2024-06, with the labels that each got.

#4450 [OU-IMP] apriori : pos_margin_account_invoice_margin merged into point_of_sale
  openupgrade_scripts/apriori.py
Labels: approved

#4451 [14.0][OU-ADD] base: web_disable_export_group migration
  openupgrade_scripts/scripts/base/14.0.1.3/group_allow_export_noupdate_changes.xml
  openupgrade_scripts/scripts/base/14.0.1.3/noupdate_changes.xml
  openupgrade_scripts/scripts/base/14.0.1.3/post-migrate.py
  openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py
Labels: approved

#4446 [15.0][OU-ADD] l10n_de_steuernummer: Merged into base_vat
  openupgrade_scripts/apriori.py
Labels: approved

#4018 [16.0][OU-ADD] google_gmail: Migration done
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/google_gmail/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/google_gmail/16.0.1.2/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4477 [16.0][FIX] base: keep translations for null src while upgrade
  openupgrade_scripts/scripts/base/16.0.1.3/end-migration.py
  openupgrade_scripts/scripts/base/16.0.1.3/pre-migration.py
Labels: approved, ready to merge
