Repository OCA/OpenUpgrade, pull requests merged in 2024-03, with the labels that each got.

#4293 [16.0][OU-ADD] stock_account: set display_type of cogs account move line
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/stock_account/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock_account/16.0.1.1/upgrade_analysis_work.txt
Labels: approved, ready to merge

#4177 [16.0][OU-ADD] website_profile: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_profile/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_profile/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#3933 [16.0] [OU-ADD] hr_attendance
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_attendance/16.0.2.0/post-migration.py
  openupgrade_scripts/scripts/hr_attendance/16.0.2.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4156 [16.0][OU-ADD] hr_expense: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_expense/16.0.2.0/post-migration.py
  openupgrade_scripts/scripts/hr_expense/16.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/hr_expense/16.0.2.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4289 [16.0][OU-ADD] project: migration script
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/project/16.0.1.2/post-migration.py
  openupgrade_scripts/scripts/project/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/project/16.0.1.2/tests/__init__.py
  openupgrade_scripts/scripts/project/16.0.1.2/tests/test_project_migration.py
  openupgrade_scripts/scripts/project/16.0.1.2/upgrade_analysis_work.txt
Labels: Dependency OK

#3958 [16.0] [OU-ADD] hr_hourly_cost
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_hourly_cost/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4029 [16.0][OU-ADD] hr_timesheet
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_timesheet/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_timesheet/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4046 [16.0][OU-ADD] hr_timesheet_attendance: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_timesheet_attendance/16.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4056 [16.0][OU-ADD] website_slides
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_slides/16.0.2.6/post-migration.py
  openupgrade_scripts/scripts/website_slides/16.0.2.6/pre-migration.py
  openupgrade_scripts/scripts/website_slides/16.0.2.6/upgrade_analysis_work.txt
Labels: Dependency OK

#4307 [14.0][OU-ADD] l10n_be_invoice_bba: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/l10n_be_invoice_bba/14.0.1.2/upgrade_analysis_work.txt
Labels: needs fixing, approved

#4329 [REM] remove rename of pos_journal_image into pos_payment_method_image, now handled in V13
  openupgrade_scripts/apriori.py
Labels: bot is merging ⏳

#4330 [IMP] pos_journal_image V12 module renamed into 'pos_payment_method_image' in V13
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: bot is merging ⏳

#4354 [FIX] account_reconciliation_widget has been renamed into account_reconcile_oca
  openupgrade_scripts/apriori.py
Labels: needs review, bot is merging ⏳

#4137 [16.0][OU-ADD] website_sale_comparison: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_comparison/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4089 [16.0][OU-ADD] website_event_sale: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_event_sale/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4067 [16.0][OU-ADD] purchase_stock: migration
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/purchase_stock/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/purchase_stock/16.0.1.2/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK

#4071 [16.0][OU-ADD] stock_landed_costs: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/stock_landed_costs/16.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4064 [16.0][OD-ADD] sale_product_configurator: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_product_configurator/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK

#4181 [16.0][OU-ADD] website_sale_wishlist: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_wishlist/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK

#4138 [16.0][OU-ADD] website_sale_product_configurator: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_product_configurator/16.0.0.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#3937 [16.0][OU-ADD] hr_fleet
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_fleet/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_fleet/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge, Dependency OK

#4015 [16.0][OU-ADD] sale_stock
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_stock/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_stock/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK
