Repository OCA/OpenUpgrade, pull requests merged in 2024-12, with the labels that each got.

#4686 [15.0][IMP] sale_stock: As we renamed the column, computation is launched
  openupgrade_scripts/scripts/sale_stock/15.0.1.0/pre-migration.py
Labels: approved

#4689 [17.0][OU-ADD] iap: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/iap/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4608 [17.0][OU-ADD] attachment_indexation: Nothing to do
  docsource/modules160-170.rst
Labels: approved, ready to merge, bot is merging ⏳, Dependency OK

#4622 [17.0][OU-ADD] sms: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sms/17.0.3.0/upgrade_analysis_work.txt
Labels: approved, Blocked by dependency, ready to merge, bot is merging ⏳

#4615 [17.0][OU-ADD] iap_mail: Nothing to do
  docsource/modules160-170.rst
Labels: approved, bot is merging ⏳, Dependency OK

#4690 [17.0][OU-ADD] barcodes, barcodes_gs1_nomenclature: nothing to do
  docsource/modules160-170.rst
Labels: Blocked by dependency, bot is merging ⏳

#4666 [17.0][OU-ADD] fleet: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/fleet/17.0.0.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4700 [17.0][OU-ADD] base_address_extended: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/base_address_extended/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4697 [17.0][OU-IMP] new analysis (december 2024)
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/base_import_module/17.0.1.0/upgrade_analysis_work.txt
Labels: needs review

#4685 [17.0][OU-ADD] sales_team: nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sales_team/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#3397 [MIG][15.0] mass_mailing_slides: migration for 15.0, nothing to do
  docsource/modules140-150.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4186 [14.0][FIX] hr_payroll_period was there in old version, so it is merged_modules in apriori
  openupgrade_scripts/apriori.py
Labels: bot is merging ⏳

#4340 [15.0][OU-ADD] purchase_requisition_stock: purchase_requisition_grouped_by_procurement compatibility
  openupgrade_scripts/scripts/purchase_requisition_stock/15.0.1.2/pre-migration.py
Labels: bot is merging ⏳

#4682 [17.0][OU-ADD] enable coverage/codecov
  .github/workflows/test.yml
Labels: approved

#4528 [15.0] [OU-IMP] hr_contract: merge hr_contract_type
  openupgrade_scripts/apriori.py
Labels: approved

#4663 [17.0][OU-ADD] event: Migration scripts
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/event/17.0.1.8/post-migration.py
  openupgrade_scripts/scripts/event/17.0.1.8/pre-migration.py
  openupgrade_scripts/scripts/event/17.0.1.8/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳, Dependency OK
