Repository OCA/OpenUpgrade, pull requests merged in 2024-07, with the labels that each got.

#4075 [16.0][OU-ADD] purchase_requisition_stock: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/purchase_requisition_stock/16.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4497 [17.0][ADD] apriori: merge purchase_discount into purchase
  openupgrade_framework/README.rst
  openupgrade_framework/readme/CONFIGURE.md
  openupgrade_framework/readme/CONFIGURE.rst
  openupgrade_framework/readme/CONTRIBUTORS.md
  openupgrade_framework/readme/CONTRIBUTORS.rst
  openupgrade_framework/readme/CREDITS.md
  openupgrade_framework/readme/CREDITS.rst
  openupgrade_framework/readme/DESCRIPTION.md
  openupgrade_framework/readme/DESCRIPTION.rst
  openupgrade_framework/readme/DEVELOP.md
  openupgrade_framework/readme/DEVELOP.rst
  openupgrade_framework/readme/INSTALL.md
  openupgrade_framework/readme/INSTALL.rst
  openupgrade_framework/static/description/index.html
  openupgrade_scripts/apriori.py
Labels: approved

#4022 [16.0][OU-ADD] website_membership: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Dependency OK

#4187 [16.0][OU-ADD] loyalty
  openupgrade_scripts/scripts/loyalty/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/loyalty/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/loyalty/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4506 [16.0][MIG] sale_loyalty_delivery: Migration to version 16.0
  openupgrade_scripts/scripts/sale_loyalty_delivery/16.0.1.0/pre-migration.py
Labels: approved

#4526 [15.0][OU-ADD] website_sale_coupon_delivery: Migration to version 15.0
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/website_sale_coupon_delivery/15.0.1.0/upgrade_analysis_work.txt
Labels: approved

#4527 [16.0][OU-ADD] website_sale_loyalty_delivery: Migration to version 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_loyalty/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_loyalty/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_loyalty/16.0.1.0/upgrade_analysis_work.txt
Labels: approved
