Repository OCA/OpenUpgrade, pull requests merged in 2024-02, with the labels that each got.

#4297 [REM] Remove URL for obsolete contents.
  README.md
Labels: approved

#4176 [16.0][OU-ADD] website_crm: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_crm/16.0.2.1/upgrade_analysis_work.txt
Labels: approved, ready to merge, Dependency OK

#4014 [16.0][OU-ADD] sale_management
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_management/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_management/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Blocked by dependency

#3996 [16.0][OU-ADD] sale_crm: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_crm/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#3985 [16.0][OU-ADD] event_sale: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/event_sale/16.0.1.2/upgrade_analysis_work.txt
Labels: approved, ready to merge

#4033 [16.0] [OU-ADD] sms: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sms/16.0.2.4/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4027 [16.0][OU-ADD] sale_margin: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_margin/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge, bot is merging ⏳, Dependency OK

#3911 [16.0][OU-ADD] hr
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr/16.0.1.1/post-migration.py
  openupgrade_scripts/scripts/hr/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/hr/16.0.1.1/tests/__init__.py
  openupgrade_scripts/scripts/hr/16.0.1.1/tests/data.py
  openupgrade_scripts/scripts/hr/16.0.1.1/tests/test_hr_migration.py
  openupgrade_scripts/scripts/hr/16.0.1.1/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4158 [16.0][OU-ADD] account_edi_ubl_cii
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/account_edi_ubl_cii/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4310 [16.0][OU-FIX] payment: install account_payment module
  openupgrade_scripts/scripts/payment/16.0.2.0/pre-migration.py
Labels: approved

#4315 [14.0][OU-IMP] *: remove obsolete SQL views
  openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/purchase/14.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/stock/14.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/website_crm_partner_assign/14.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_event_questions/14.0.1.1/pre-migration.py
Labels: approved

#4285 [OU-IMP] apriori : OCA/pos_journal_image renamed into OCA/pos_payment_method_image
  openupgrade_scripts/apriori.py
Labels: approved

#4316 [16.0][OU-IMP] sale: remove obsolete SQL views
  openupgrade_scripts/scripts/sale/16.0.1.2/pre-migration.py
Labels: approved

#4265 [OU-ADD] l10n_fr
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/l10n_fr/16.0.2.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_fr/16.0.2.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4266 [OU-ADD] pos_restaurant : Nothing to do
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/pos_restaurant/15.0.1.0/upgrade_analysis_work.txt
Labels: approved, ready to merge

#4318 [16.0][OU-ADD] mail_preview_base + mail_preview_audio: Merged into mail
  openupgrade_scripts/apriori.py
Labels: approved

#3954 [16.0] [OU-ADD] hr_maintenance: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_maintenance/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#3968 [16.0][OU-ADD] hr_org_chart: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_org_chart/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4314 [13.0][ADD] apriori: Change name of quality_control_team to quality_control_team_oca
  odoo/addons/openupgrade_records/lib/apriori.py
Labels: approved

#4320 [FIX] pre-commit
  openupgrade_scripts/scripts/hr_maintenance/16.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/hr_org_chart/16.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/maintenance/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4291 [16.0][OU-ADD] stock
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/stock/16.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/16.0.1.1/upgrade_analysis_work.txt
Labels: approved, ready to merge, bot is merging ⏳

#3987 [16.0][OU-ADD] hr_gamification: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_gamification/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4026 [16.0] [OU-ADD] gamification_sale_crm: nothing to do
  docsource/modules150-160.rst
Labels: Dependency OK

#4024 [16.0] [OU-ADD] website_livechat: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_livechat/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#3947 [16.0][OU-ADD] fleet
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/fleet/16.0.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/fleet/16.0.0.1/post-migration.py
  openupgrade_scripts/scripts/fleet/16.0.0.1/pre-migration.py
  openupgrade_scripts/scripts/fleet/16.0.0.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4308 [14.0][OU-ADD] l10n_be: nothing to do
  docsource/modules130-140.rst
  openupgrade_scripts/scripts/l10n_be/14.0.2.0/upgrade_analysis_work.txt
Labels: approved

#4303 [16.0][OU-ADD] purchase: Migration scripts
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/purchase/16.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/purchase/16.0.1.2/upgrade_analysis_work.txt
Labels: Dependency OK
