Repository OCA/OpenUpgrade, pull requests merged in 2025-07, with the labels that each got.

#5160 [18.0][MIG] Several mail dependent modules
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/google_gmail/18.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/link_tracker/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mail_bot/18.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mail_group/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/privacy_lookup/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5162 [18.0][OU-ADD] maintenance
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/maintenance/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5164 [18.0][OU-ADD] snailmail_account
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/snailmail_account/18.0.0.1/upgrade_analysis_work.txt
Labels: Nothing to do

#5166 [17.0][OU-FIX] account: map column chart_template_id
  openupgrade_scripts/scripts/account/17.0.1.2/post-migration.py
Labels: approved

#5163 [17.0][OU-FIX] account: assign xmlid to journals
  openupgrade_scripts/scripts/account/17.0.1.2/end-migration.py
Labels: approved

#5173 [18.0][OU-ADD] Several sms-related modules
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/calendar_sms/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/event_sms/18.0.1.0/post-migrate.py
  openupgrade_scripts/scripts/event_sms/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/pos_sms/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/stock_sms/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4107 [16.0][FIX] openupgrade_framework : end-migration scripts are forced …
  .github/workflows/test.yml
  openupgrade_framework/odoo_patch/odoo/modules/migration.py
  openupgrade_scripts/scripts/base/16.0.1.3/tests/__init__.py
  openupgrade_scripts/scripts/base/16.0.1.3/tests/end-migration_test.py
  openupgrade_scripts/scripts/base/16.0.1.3/tests/test_newly_installed_end_migration.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#5169 [17.0][FIX] hr_attendance: omitted group
  openupgrade_scripts/scripts/hr_attendance/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/hr_attendance/17.0.2.0/upgrade_analysis_work.txt
Labels: needs review, approved

#5175 [18.0][OU-ADD] The ubl-related modules
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/account_edi_ubl_cii_tax_extension/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/purchase_edi_ubl_bis3/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sale_edi_ubl/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5183 [18.0][OU-ADD] website
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/social_media/18.0.0.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/website/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5184 [17.0][OU-ADD] l10n_dk
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/l10n_dk/17.0.1.3/post-migration.py
  openupgrade_scripts/scripts/l10n_dk/17.0.1.3/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/l10n_es/17.0.5.4/upgrade_analysis_work.txt
Labels: Dependency OK

#5159 [18.0][OU-ADD] apriori: product_supplierinfo_import_by_barcode renamed to product_supplierinfo_import
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge, Dependency OK

#5193 [18.0][OU-ADD] mass_mailing
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/mass_mailing/18.0.2.7/noupdate_changes_work.xml
  openupgrade_scripts/scripts/mass_mailing/18.0.2.7/post-migrate.py
  openupgrade_scripts/scripts/mass_mailing/18.0.2.7/upgrade_analysis_work.txt
Labels: Dependency OK

#5196 [18.0][OU-ADD] repair
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/repair/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/repair/18.0.1.0/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳, Dependency OK

#5198 [18.0][OU-ADD] payment_paypal
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/payment_paypal/18.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_paypal/18.0.2.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5200 [18.0][OU-ADD] payment_adyen
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/payment_adyen/18.0.2.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5201 [18.0][MIG] mass_mailing_*
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/mass_mailing_crm/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mass_mailing_crm_sms/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mass_mailing_sale/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mass_mailing_sale_sms/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mass_mailing_sms/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/mass_mailing_themes/18.0.1.2/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5202 [18.0][OU-ADD] membership
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/membership/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5203 [18.0][OU-ADD] project
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/analytic/18.0.1.2/end-migration.py
  openupgrade_scripts/scripts/project/18.0.1.3/post-migration.py
  openupgrade_scripts/scripts/project/18.0.1.3/pre-migration.py
  openupgrade_scripts/scripts/project/18.0.1.3/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#5224 [18.0][OU-ADD] iap_crm: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/iap_crm/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5038 [18.0][OU-ADD] project_hr_expense: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/project_hr_expense/18.0.1.0/upgrade_analysis_work.txt
Labels: approved, Nothing to do, Dependency OK

#5219 [18.0][OU-ADD] website_sale_product_attachment: Merged into website_sale
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/website_sale/18.0.1.1/post-migration.py
Labels: Dependency OK

#5226 [18.0][OU-ADD] microsoft_account,microsoft_outlook: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/microsoft_account/18.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/microsoft_outlook/18.0.1.1/upgrade_analysis.txt
Labels: Nothing to do, Dependency OK

#5225 [18.0][OU-ADD] crm_iap_enrich,crm_iap_mine: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/crm_iap_enrich/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/crm_iap_mine/18.0.1.2/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5239 [17.0][OU-FIX] sale: Update also sale.order.line~state
  openupgrade_scripts/scripts/sale/17.0.1.2/post-migration.py
Labels: approved

#5233 [18.0][OU-ADD] sale_margin: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_margin/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5176 [18.0][OU-ADD] sale_pdf_quote_builder
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_pdf_quote_builder/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_pdf_quote_builder/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5236 [18.0][OU-ADD] sale_timesheet: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_timesheet/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5254 [17.0][OU-ADD] sale_report_country_state: Merged into sale
  openupgrade_scripts/apriori.py
Labels: approved, Dependency OK

#5249 [18.0][OU-ADD] website_blog: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/website_blog/18.0.1.1/upgrade_analysis_work.txt
Labels: approved, Nothing to do, Dependency OK

#5257 [18.0][OU-ADD] website_project: Migration to 18.0. Renamed from website_form_project
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/website_project/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_project/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK
