Repository OCA/OpenUpgrade, pull requests merged in 2025-01, with the labels that each got.

#4706 [OU-FIX] apriori: l10n_it_dichiarazione_intento renamed to
  openupgrade_scripts/apriori.py
Labels: approved, bot is merging ⏳

#4711 [16.0][FIX] stock: switch groups
  openupgrade_scripts/scripts/stock/16.0.1.1/post-migration.py
Labels: approved

#4708 [17.0][OU-IMP] event: Finish migration scripts
  openupgrade_scripts/scripts/event/17.0.1.8/post-migration.py
  openupgrade_scripts/scripts/event/17.0.1.8/upgrade_analysis_work.txt
Labels: approved, ready to merge, bot is merging ⏳

#4667 [16.0][FIX] base: avoid ignoring right translations
  openupgrade_scripts/scripts/base/16.0.1.3/pre-migration.py
Labels: bot is merging ⏳

#4641 [OU-ADD] spreadsheet. Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/spreadsheet/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4565 [17.0][OU-ADD] calendar_sms: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/calendar_sms/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4714 [17.0][OU-ADD] link_tracker: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/link_tracker/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4715 [17.0][OU-ADD] im_livechat
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/im_livechat/17.0.1.0/end-migration.py
  openupgrade_scripts/scripts/im_livechat/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/im_livechat/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/im_livechat/17.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4717 [17.0][OU-ADD] gamification
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/gamification/17.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/gamification/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/gamification/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/gamification/17.0.1.0/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳, Dependency OK

#4718 [17.0][OU-IMP] base: avoid pylint relative-import
  openupgrade_scripts/scripts/base/17.0.1.3/pre-migration.py
  openupgrade_scripts/scripts/gamification/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/gamification/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4048 [16.0][OU-ADD] hr_presence
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_presence/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_presence/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4720 [16.0][OU-ADD] sale_timesheet_margin: nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4721 [16.0][MIG] account_sale_timesheet
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4722 [16.0][MIG] crm_mail_plugin
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4723 [16.0][MIG] crm_sms
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4054 [16.0][OU-ADD] hr_skills_slides: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_skills_slides/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4076 [16.0] [OU-ADD] website_jitsi: nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_jitsi/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4719 [16.0][OU-IMP] hr: Convert hr_plan_activity_type records without data loss
  openupgrade_scripts/scripts/hr/16.0.1.1/post-migration.py
  openupgrade_scripts/scripts/hr/16.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/hr/16.0.1.1/upgrade_analysis_work.txt
Labels: needs review

#4065 [16.0][OU-ADD] website_twitter: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#3974 [16.0][OU-ADD] event_booth: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/event_booth/16.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#3972 [16.0][OU-ADD] event_booth_sale: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/event_booth_sale/16.0.1.1/post-migration.py
  openupgrade_scripts/scripts/event_booth_sale/16.0.1.1/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳, Dependency OK
