Repository OCA/OpenUpgrade, pull requests merged in 2025-04, with the labels that each got.

#4908 [17.0][OU-ADD] hr_timesheet: Migration scripts
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_timesheet/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_timesheet/17.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4907 [17.0][OU-ADD] spreadsheet_dashboard_hr_timesheet: Nothing to do
  docsource/modules160-170.rst
Labels: Blocked by dependency

#4910 [17.0][OU-ADD] sale_timesheet: Migration scripts to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_timesheet/17.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/sale_timesheet/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_timesheet/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_timesheet/17.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4883 [18.0][IMP] apriori: fill it accordingly
  docsource/modules170-180.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/base/18.0.1.3/post-migration.py
  openupgrade_scripts/scripts/base/18.0.1.3/pre-migration.py
  openupgrade_scripts/scripts/base/18.0.1.3/upgrade_analysis_work.txt
Labels: needs review

#4913 [17.0][OU-ADD] hr_timesheet_attendance: Migration scripts to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_timesheet_attendance/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/hr_timesheet_attendance/17.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4943 [17.0][OU-FIX] point_of_sale: check if pos_restaurant is installed
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/pre-migration.py
Labels: bot is merging ⏳, Dependency OK

#4944 [18.0][OU-ADD] onboarding
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/onboarding/18.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4945 [18.0][OU-ADD] resource
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/resource/18.0.1.1/post-migration.py
  openupgrade_scripts/scripts/resource/18.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4947 [18.0][OU-ADD] auth_signup
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/auth_signup/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/auth_signup/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4949 [18.0][OU-ADD] portal
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/portal/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/portal/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4951 [18.0][OU-ADD] barcodes & barcodes_gs1_nomenclature
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/barcodes/18.0.2.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/barcodes_gs1_nomenclature/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4952 [15.0] [IMP] Update pre-commit packages
  .pre-commit-config.yaml
  .pylintrc
  openupgrade_framework/odoo_patch/odoo/api.py
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/point_of_sale/15.0.1.0.1/post-migration.py
  openupgrade_scripts/scripts/website/15.0.1.0/post-migration.py
Labels: bot is merging ⏳

#4841 [18.0][OU-ADD] analytic
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/analytic/18.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/analytic/18.0.1.2/post-migration.py
  openupgrade_scripts/scripts/analytic/18.0.1.2/upgrade_analysis_work.txt
Labels: Dependency OK

#4965 [17.0][IMP] apriori: `delivery_carrier_customer_info` renamed to `partner_delivery_info`
  openupgrade_scripts/apriori.py
Labels: Dependency OK

#4966 [18.0][IMP] apriori: renamed modules
  openupgrade_scripts/apriori.py
Labels: approved

#4748 [17.0][OU-ADD] apriori: 10n_de_skr03_mis_reports + l10n_de_skr04_mis_reports: Merged into l10n_de_mis_reports
  openupgrade_scripts/apriori.py
Labels: approved, Dependency OK

#4969 [18.0][OU-ADD] calendar
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/calendar/18.0.1.1/post-migration.py
  openupgrade_scripts/scripts/calendar/18.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4968 [18.0][OU-ADD] spreadsheet
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/spreadsheet/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK
