Repository OCA/OpenUpgrade, pull requests merged in 2025-06, with the labels that each got.

#5086 [17.0][OU-FIX] analytic: search for existing default project analytic plan
  openupgrade_scripts/scripts/analytic/17.0.1.2/pre-migration.py
Labels: approved

#5091 [17.0][OU-FIX] base: error on pre-migration file
  openupgrade_scripts/scripts/base/17.0.1.3/pre-migration.py
Labels: approved

#5107 [14.0][OU-ADD] apriori: merge helpdesk_mgmt_timesheet_time_control into helpdesk_mgmt_timesheet
  openupgrade_scripts/apriori.py
Labels: approved

#5111 [17.0][OU-ADD] iap_crm
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/iap_crm/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do

#4960 [18.0][OU-ADD] apriori: project_stock renamed to project_task_stock + project_stock_product_set renamed to project_task_stock_product_set
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge, Dependency OK

#5088 [18.0][OU-FIX] stock: adapt location_final_id
  openupgrade_scripts/scripts/stock/18.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/18.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/18.0.1.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/stock/tests/data_pull.py
  openupgrade_scripts/scripts/stock/tests/data_push.py
  openupgrade_scripts/scripts/stock/tests/test_migration.py
Labels: needs review

#5097 [18.0][OU-ADD] web_hierarchy: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/web_hierarchy/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5093 [18.0][OU-ADD] account_edi: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/account_edi/18.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#5096 [18.0][OU-ADD] attachment_indexation: Nothing to do
  docsource/modules170-180.rst
Labels: Dependency OK

#5030 [18.0][OU-ADD] gamification_sale_crm: Nothing to do
  docsource/modules170-180.rst
Labels: approved, Dependency OK

#5089 [18.0][OU-ADD] purchase_stock
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/purchase_stock/18.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase_stock/18.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/purchase_stock/18.0.1.2/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#5092 [18.0][OU-ADD] mrp
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/mrp/18.0.2.0/post-migration.py
  openupgrade_scripts/scripts/mrp/18.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/mrp/18.0.2.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5125 [18.0][OU-ADD] sale_purchase_stock
  docsource/modules170-180.rst
Labels: Blocked by dependency, Nothing to do

#5104 [18.0][OU-ADD] point_of_sale
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/point_of_sale/18.0.1.0.2/post-migration.py
  openupgrade_scripts/scripts/point_of_sale/18.0.1.0.2/pre-migration.py
  openupgrade_scripts/scripts/point_of_sale/18.0.1.0.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/product/18.0.1.2/post-migration.py
  openupgrade_scripts/scripts/product/18.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/product/18.0.1.2/upgrade_analysis_work.txt
Labels: needs review, Dependency OK
