Repository OCA/OpenUpgrade, pull requests merged in 2025-02, with the labels that each got.

#4668 [17.0][OU-ADD] account: Migration to 17.0
  .prettierignore
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account/17.0.1.2/noupdate_changes_work.xml
  openupgrade_scripts/scripts/account/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/account/tests/data_account_migration.py
  openupgrade_scripts/scripts/account/tests/test_account_migration.py
Labels: needs review, approved, ready to merge, Dependency OK

#4730 [15.0][OU-FIX] hr_holidays: forgot to call a method
  openupgrade_scripts/scripts/hr_holidays/15.0.1.5/post-migration.py
Labels: bot is merging ⏳

#4698 [17.0][OU-ADD] apriori: l10n_generic_coa to account
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
Labels: approved, bot is merging ⏳, Dependency OK

#4692 [17.0][OU-ADD] payment: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/payment/17.0.2.0/end-migration.py
  openupgrade_scripts/scripts/payment/17.0.2.0/noupdate_changes_work.xml
  openupgrade_scripts/scripts/payment/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment/17.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/payment/17.0.2.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/payment/tests/data_payment_migration.py
  openupgrade_scripts/scripts/payment/tests/test_payment_migration.py
Labels: bot is merging ⏳, Dependency OK

#4656 [17.0][OU-ADD] mail_activity_plan: Merged into mail
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/mail/17.0.1.15/post-migration.py
  openupgrade_scripts/scripts/mail/17.0.1.15/pre-migration.py
Labels: needs review, bot is merging ⏳, Dependency OK

#4362 [16.0][OU-IMP] project: bump version to 1.3
  openupgrade_scripts/scripts/project/16.0.1.2/noupdate_changes.xml
  openupgrade_scripts/scripts/project/16.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/project/16.0.1.3/post-migration.py
  openupgrade_scripts/scripts/project/16.0.1.3/pre-migration.py
  openupgrade_scripts/scripts/project/16.0.1.3/tests/__init__.py
  openupgrade_scripts/scripts/project/16.0.1.3/tests/test_project_migration.py
  openupgrade_scripts/scripts/project/16.0.1.3/upgrade_analysis_work.txt
Labels: needs review, approved, ready to merge, bot is merging ⏳

#4734 [17.0][FIX] avoid test failures resulting from not yet migrated localizations
  .github/workflows/test.yml
Labels: bot is merging ⏳

#4733 [17.0][OU-ADD] stock_account: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/stock_account/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock_account/17.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock_account/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4739 [16.0][OU-IMP] purchase_requisition: link purchase orders based on deprecated requisition type
  docsource/modules150-160.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/purchase_requisition/16.0.0.1/post-migration.py
  openupgrade_scripts/scripts/purchase_requisition/16.0.0.1/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/purchase_requisition_stock/16.0.1.2/upgrade_analysis_work.txt
Labels: needs review, bot is merging ⏳

#4610 [17.0][OU-ADD] base_iban: Nothing to do
  docsource/modules160-170.rst
Labels: approved, ready to merge, bot is merging ⏳, Dependency OK

#4554 [17.0][OU-ADD] crm: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/crm/17.0.1.8/pre-migration.py
  openupgrade_scripts/scripts/crm/17.0.1.8/upgrade_analysis_work.txt
Labels: Blocked by dependency, bot is merging ⏳

#4589 [17.0][OU-ADD] crm_sms: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/crm_sms/17.0.1.1/upgrade_analysis_work.txt
Labels: approved, Blocked by dependency, bot is merging ⏳

#4650 [17.0][OU-ADD] account_payment: Migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account_payment/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/account_payment/17.0.2.0/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Dependency OK

#4691 [17.0][OU-ADD] sale: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/sale/17.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sale/tests/data_sale_migration.py
  openupgrade_scripts/scripts/sale/tests/test_sale_migration.py
Labels: approved, bot is merging ⏳, Dependency OK

#4745 [17.0][OU-MIG] sale_stock
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_stock/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4699 [17.0][OU-ADD] purchase: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase/17.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/purchase/17.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4746 [17.0][OU-ADD] purchase_stock: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase_stock/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/purchase_stock/17.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4634 [17.0][OU-ADD] sale_management: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_management/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4749 [17.0][OU-FIX] sale_stock: Missing migration script
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_stock/17.0.1.0/post-migration.py
Labels: needs review, bot is merging ⏳

#4753 [17.0][MIG] social_media
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/social_media/17.0.0.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4754 [17.0][MIG] sale_crm
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_crm/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4613 [17.0][OU-ADD] gamification_sale_crm: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4755 [17.0][MIG] sale_purchase
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_purchase/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4621 [17.0][OU-ADD] sale_purchase_stock : Nothing to do
  docsource/modules160-170.rst
Labels: approved, bot is merging ⏳, Nothing to do, Dependency OK

#4646 [17.0][OU-ADD] snailmail: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/snailmail/17.0.0.4/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4654 [17.0][OU-ADD] maintenance: Migration scripts
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/maintenance/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/maintenance/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/maintenance/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4756 [17.0][OU-IMP] purchase_stock: Fill incoterm_location
  openupgrade_scripts/scripts/purchase_stock/17.0.1.2/post-migration.py
Labels: bot is merging ⏳

#4758 [17.0][OU-ADD] mail_activity_unlink_log: Rename to mail_activity_cancel_tracking
  openupgrade_scripts/apriori.py
Labels: approved, bot is merging ⏳

#4762 [17.0][OU-FIX] mail: set outgoing emails
  openupgrade_scripts/scripts/mail/17.0.1.15/post-migration.py
  openupgrade_scripts/scripts/mail/17.0.1.15/upgrade_analysis_work.txt
Labels: needs review

#4780 [17.0][OU-ADD] base_sparse_field: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/base_sparse_field/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4771 [17.0][OU-ADD] account_edi: Migration to 17
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account_edi/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/account_edi/17.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4772 [17.0][OU-ADD] sale_margin: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_margin/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Nothing to do, Dependency OK

#4778 [17.0][OU-ADD] account_check_printing: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account_check_printing/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4777 [17.0][OU-ADD] portal_rating: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/portal_rating/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4779 [17.0][OU-ADD] stock_picking_batch: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/stock_picking_batch/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4767 [17.0][OU-ADD] auth_oauth: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/auth_oauth/17.0.1.0/upgrade_analysis_done.txt
Labels: Nothing to do, Dependency OK

#4782 [17.0][OU-ADD] product_expiry: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/product_expiry/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4556 [13.0][OU-ADD] product_email_template
  addons/product_email_template/migrations/13.0.1.0/post-migration.py
  odoo/openupgrade/doc/source/modules120-130.rst
Labels: Dependency OK

#4789 [13.0][FIX] github workflows actions
  .github/workflows/documentation.yml
  .github/workflows/flake.yml
  .github/workflows/test.yml
  addons/stock/migrations/13.0.1.1/post-migration.py
  addons/website/migrations/13.0.1.0/post-migration.py
Labels: approved

#4534 [FIX] account: reversed_entry_id migration was reversed
  addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt
  addons/account/migrations/13.0.1.1/post-migration.py
  addons/account/migrations/13.0.1.1/pre-migration.py
Labels: needs review

#4792 [17.0][OU-FIX] account: Rename XML-IDs for installed CoA elements
  openupgrade_scripts/scripts/account/17.0.1.2/post-migration.py
Labels: approved
