Repository OCA/OpenUpgrade, pull requests merged in 2025-08, with the labels that each got.

#5237 [18.0][OU-ADD] hr_timesheet_attendance: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/hr_timesheet_attendance/18.0.1.1/upgrade_analysis_work.txt
Labels: Nothing to do

#5270 [18.0][OU-ADD] sale_loyalty: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_loyalty/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5271 [18.0][OU-ADD] website_sale_loyalty: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/website_sale_loyalty/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5277 [18.0][OU-ADD] hr_calendar
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/hr_calendar/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5102 [18.0][OU-ADD] survey
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/survey/18.0.3.7/post-migration.py
  openupgrade_scripts/scripts/survey/18.0.3.7/upgrade_analysis_work.txt
Labels: Dependency OK

#5127 [18.0][OU-ADD] hr_attendance_autoclose: Merged into hr_attendance
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/hr_attendance/18.0.2.0/post-migration.py
Labels: approved, Dependency OK

#5256 [18.0][OU-ADD] website_slides_survey : Migration to 18.0
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/website_slides_survey/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_slides_survey/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5283 [17.0][OU-FIX] payment: assign payment_method_ids on duplicated providers
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/payment/17.0.2.0/noupdate_changes_work.xml
  openupgrade_scripts/scripts/payment/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_custom/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_demo/17.0.2.0/noupdate_changes.xml
  openupgrade_scripts/scripts/payment_demo/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_demo/17.0.2.0/upgrade_analysis_work.txt
Labels: needs review, approved

#5294 [18.0][OU-ADD] hr_recruitment_survey : Migration to 18.0
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/hr_recruitment_survey/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_recruitment_survey/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5295 [18.0][OU-ADD] auth_password_policy: Nothing to do
  docsource/modules170-180.rst
Labels: Nothing to do, Dependency OK

#5303 [17.0][OU-ADD] hr_recruitment_skills : Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_recruitment_skills/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Nothing to do

#5302 [18.0][OU-ADD] hr_recruitment_skills : Migration to 18.0
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/hr_recruitment_skills/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_recruitment_skills/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_recruitment_skills/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#5320 [18.0][OU-ADD] pos_restaurant : Migration to 18.0
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/pos_restaurant/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/pos_restaurant/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/pos_restaurant/18.0.1.0/upgrade_analysis_work.txt
Labels: approved

#5221 [18.0][OU-ADD] spreadsheet_dashboard_hr_timesheet, spreadsheet_dashboard_sale_timesheet: Nothing to do
  docsource/modules170-180.rst
Labels: Nothing to do, Dependency OK

#5310 [18.0][OU-ADD] fleet: Migration to 18.0
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/fleet/18.0.0.1/post-migration.py
  openupgrade_scripts/scripts/fleet/18.0.0.1/upgrade_analysis_work.txt
Labels: approved

#5348 [18.0][OU-ADD] website_forum: Migration scripts
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/website_forum/18.0.1.2/post-migration.py
  openupgrade_scripts/scripts/website_forum/18.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/website_forum/18.0.1.2/upgrade_analysis_work.txt
Labels: approved

#4964 [16.0][IMP] apriori: renamed modules (`product_packaging_level` + `sell_only_by_packaging`)
  openupgrade_scripts/apriori.py
Labels: Dependency OK
