Repository OCA/OpenUpgrade, pull requests merged in 2025-05, with the labels that each got.

#4972 [18.0][OU-FIX] calendar: forgot calling delete_records_safely_by_xml_id
  openupgrade_scripts/scripts/calendar/18.0.1.1/post-migration.py
Labels: bot is merging ⏳, Dependency OK

#4974 [17.0][OU-ADD] product_margin: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/product_margin/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4975 [17.0][OU-ADD] website_sale_delivery: Migration to 17.0 (merged into website_sale)
  docsource/modules160-170.rst
Labels: Dependency OK

#4977 [18.0][OU-FIX] base: add missing SQL to fix view mode in ir_act_window
  openupgrade_scripts/scripts/base/18.0.1.3/pre-migration.py
Labels: approved

#4962 [18.0][IMP] apriori: commission -> commission_oca
  openupgrade_scripts/apriori.py
Labels: Dependency OK

#4981 [16.0][OU-ADD] mass_mailing_slides : Nothing to do
  docsource/modules150-160.rst
Labels: Nothing to do, Dependency OK

#4983 [17.0][OU-ADD] website_sale_slides: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_sale_slides/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4982 [16.0][OU-ADD] sale_quotation_builder : Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/sale_quotation_builder/16.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/sale_quotation_builder/16.0.1.0/upgrade_analysis.txt
Labels: Dependency OK

#4979 [16.0][OU-ADD] website_sale_slides: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_sale_slides/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_sale_slides/16.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4980 [16.0][OU-ADD] website_slides_survey: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_slides/16.0.2.6/end-migration.py
  openupgrade_scripts/scripts/website_slides/16.0.2.6/pre-migration.py
  openupgrade_scripts/scripts/website_slides/16.0.2.6/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/website_slides_survey/16.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_slides_survey/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/website_slides_survey/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4999 [18.0][OU-ADD] phone_validation
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/phone_validation/18.0.2.1/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5000 [18.0][OU-ADD] web_unsplash
  docsource/modules170-180.rst
Labels: Nothing to do, Dependency OK

#5002 [18.0][OU-ADD] auth_top
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/auth_totp/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4958 [18.0][OU-ADD] payment
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/payment/18.0.2.0/noupdate_changes_manual.xml
  openupgrade_scripts/scripts/payment/18.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment/18.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/payment/18.0.2.0/upgrade_analysis_work.txt
Labels: needs review, approved, Dependency OK

#5004 [17.0][OU-IMP] website_event: Add script to insert default event questions for old events
  openupgrade_scripts/scripts/website_event/17.0.1.4/post-migration.py
Labels: approved

#5014 [17.0][OU-FIX] hr: set private address data from private partners
  openupgrade_scripts/scripts/hr/17.0.1.1/post-migration.py
Labels: approved

#4839 [18.0][OU-ADD] product
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/product/18.0.1.2/post-migration.py
  openupgrade_scripts/scripts/product/18.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/product/18.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/product/tests/data.py
  openupgrade_scripts/scripts/product/tests/test_migration.py
Labels: approved, Dependency OK

#5021 [17.0][OU-FIX] point_of_sale: group account move, duplicate with more…
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/post-migration.py
Labels: approved

#5031 [17.0][OU-ADD] website_sale_invoice_address: Merged into website_sale
  openupgrade_scripts/apriori.py
Labels: approved

#4995 [17.0][OU-ADD] sale_quotation_builder > sale_pdf_quote_builder: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/sale_pdf_quote_builder/17.0.1.0/upgrade_analysis.txt
Labels: approved

#5026 [18.0][OU-ADD] gamification: Nothing to do
  docsource/modules170-180.rst
Labels: Nothing to do, Dependency OK

#5039 [18.0][OU-FIX] gamification: finish migration
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/gamification/18.0.1.0/post-migration.py
Labels: bot is merging ⏳, Dependency OK

#5015 [18.0][OU-ADD] crm
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/crm/18.0.1.8/post-migrate.py
  openupgrade_scripts/scripts/crm/18.0.1.8/upgrade_analysis_work.txt
Labels: Dependency OK

#5035 [17.0][FIX] hr_attendance: Define the corresponding groups in the menus
  openupgrade_scripts/scripts/hr_attendance/17.0.2.0/post-migration.py
Labels: needs review, approved

#5040 [15.0][OU-FIX] mail: avoid duplication error in mail_group_moderation_rel query
  openupgrade_scripts/scripts/mail/15.0.1.5/pre-migration.py
Labels: needs review

#5048 [17.0][FIX] analytic: rename account.analytic.plan#default_applicability
  openupgrade_scripts/scripts/analytic/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/analytic/17.0.1.2/pre-migration.py
Labels: approved

#5047 [15.0][OU-ADD] repair: Migration to 15.0
  docsource/modules140-150.rst
  openupgrade_scripts/scripts/repair/15.0.1.0/post-migration.py
  openupgrade_scripts/scripts/repair/15.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/repair/15.0.1.0/upgrade_analysis_work.txt
Labels: approved

#5043 [16.0][OU-FIX] hr: Avoid creating work contacts without data (email + phone)
  openupgrade_scripts/scripts/hr/16.0.1.1/post-migration.py
Labels: approved

#5049 [18.0][OU-ADD] event
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/event/18.0.1.9/post-migration.py
  openupgrade_scripts/scripts/event/18.0.1.9/pre-migration.py
  openupgrade_scripts/scripts/event/18.0.1.9/upgrade_analysis_work.txt
Labels: Dependency OK

#5033 [16.0][OU-IMP] analytic: Define the appropriate value for the root_plan_id field in the analytical accounts.
  openupgrade_scripts/scripts/analytic/16.0.1.1/post-migration.py
Labels: needs review

#5001 [18.0][OU-ADD] iap
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/iap/18.0.1.1/end-migration.py
  openupgrade_scripts/scripts/iap/18.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/iap/18.0.1.1/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#5056 [18.0][OU-ADD] snailmail
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/iap_mail/18.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/snailmail/18.0.0.4/upgrade_analysis_work.txt
Labels: Dependency OK

#5055 [18.0][OU-ADD] sms
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sms/18.0.3.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5057 [18.0][OU-ADD] partner_autocomplete
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/partner_autocomplete/18.0.1.1/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5060 [18.0][OU-ADD] resource_mail
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/resource_mail/18.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#5058 [18.0][ADD] install phonenumbers in ci as it's a hard dependency for account_peppol by now
  .github/workflows/test.yml
Labels: bot is merging ⏳

#5065 [17.0][OU-ADD] microsoft_account : Nothing to do
  docsource/modules160-170.rst
Labels: Nothing to do, Dependency OK

#5066 [17.0][OU-ADD] microsoft_calendar : Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/microsoft_calendar/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/microsoft_calendar/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#5081 [18.0][OU-ADD] base_iban
  docsource/modules170-180.rst
Labels: Nothing to do, Dependency OK

#4957 [18.0][OU-ADD] stock
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/stock/18.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock/18.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock/18.0.1.1/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#5072 [18.0][OU-ADD] stock_account
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/stock_account/18.0.1.1/end-migration.py
  openupgrade_scripts/scripts/stock_account/18.0.1.1/post-migration.py
  openupgrade_scripts/scripts/stock_account/18.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/stock_account/18.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#5045 [18.0][OU-ADD] sale_crm: Nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_crm/18.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#5076 [18.0][OU-FIX] account: Fix SQL error in post-migration script on PostgreSQL 13
  openupgrade_scripts/scripts/account/18.0.1.3/post-migration.py
Labels: needs review

#5083 [18.0][OU-ADD] sale_stock
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/sale_stock/18.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_stock/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/sale_stock/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK
