Repository OCA/OpenUpgrade, pull requests merged in 2025-03, with the labels that each got.

#4796 [17.0][OU-ADD] exclude analytic 1.2 migration
  openupgrade_framework/odoo_patch/odoo/modules/migration.py
Labels: approved

#4592 [OU-ADD] payment_custom: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/payment_custom/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/payment_custom/17.0.2.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4794 [17.0][OU-ADD] hr: Migration scripts
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr/17.0.1.1/noupdate_changes.xml
  openupgrade_scripts/scripts/hr/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/hr/17.0.1.1/pre-migration.py
  openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4599 [15.0][OU-ADD] apriori: account_invoice_report_utm_campaign renamed to account_invoice_report_utm
  openupgrade_scripts/apriori.py
Labels: approved, ready to merge, bot is merging ⏳, Dependency OK

#4770 [17.0][OU-ADD] board: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/board/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Blocked by dependency, ready to merge

#4802 [17.0][OU-IMP] base, account: some fixes
  openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/base/17.0.1.3/pre-migration.py
Labels: needs review

#4805 [17.0][OU-ADD] account_invoice_fiscal_position_update: Merged into account
  openupgrade_scripts/apriori.py
Labels: approved

#4810 [17.0][OU-MIG] web_hierarchy
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/web_hierarchy/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4590 [17.0][OU-ADD] hr_org_chart: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_org_chart/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4804 [17.0][OU-FIX] product: Fixing table name ir_model_data
  openupgrade_scripts/scripts/product/17.0.1.2/post-migration.py
Labels: needs review, approved

#4809 [17.0][OU-ADD] maintenance_plan_employee: Merged into maintenance
  openupgrade_scripts/apriori.py
Labels: approved, bot is merging ⏳

#4648 [17.0][OU-ADD] sale_product_configurator: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_product_configurator/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4623 [17.0][OU-ADD] snailmail_account: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/snailmail_account/17.0.0.1/upgrade_analysis_work.txt
Labels: approved, bot is merging ⏳, Nothing to do, Dependency OK

#4813 [17.0][OU-ADD] microsoft_outlook: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/microsoft_outlook/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4751 [17.0][MIG] stock_delivery
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/delivery/17.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/delivery/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/delivery/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/delivery/17.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/stock_delivery/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4785 [17.0][OU-ADD] mass_mailing: Migration to 17.0.
  openupgrade_scripts/scripts/mass_mailing/17.0.2.7/post-migration.py
  openupgrade_scripts/scripts/mass_mailing/17.0.2.7/pre-migration.py
  openupgrade_scripts/scripts/mass_mailing/17.0.2.7/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4812 [17.0][OU-ADD] account_edi_ubl_cii: Migrate to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account_edi_ubl_cii/17.0.1.0/end-migration.py
  openupgrade_scripts/scripts/account_edi_ubl_cii/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/account_edi_ubl_cii/17.0.1.0/upgrade_analysis_work.txt
Labels: needs review, Dependency OK

#4619 [17.0][OU-ADD] purchase_requisition: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase_requisition/17.0.0.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4814 [17.0][OU-MIG] purchase_requisition_stock
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase_requisition_stock/17.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4815 [17.0][OU-MIG] (sale/purchase_)product_matrix
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase_product_matrix/17.0.1.0/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/sale_product_matrix/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4607 [17.0][OU-ADD] account_qr_code_sepa: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4021 [16.0][OU-ADD] website_mail_group: Nothing to do
  docsource/modules150-160.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4035 [16.0][OU-ADD] product_matrix: Nothing to do
  docsource/modules150-160.rst
Labels: Nothing to do, Dependency OK

#4702 [17.0][OU-ADD] hr_holidays: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/noupdate_changes.xml
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/post-migration.py
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
Labels: approved, Dependency OK

#4616 [17.0][OU-ADD] mail_bot_hr: Nothing to do
  docsource/modules160-170.rst
Labels: approved, bot is merging ⏳, Dependency OK

#4172 [16.0][OU-ADD] hr_work_entry_contract: Migration to 16.0
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/hr_work_entry_contract/16.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/hr_work_entry_contract/16.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4819 [16.0][MIG] website_crm_partner_assign
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/website_crm_partner_assign/16.0.1.2/pre-migration.py
  openupgrade_scripts/scripts/website_crm_partner_assign/16.0.1.2/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4818 [17.0][MIG] survey
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/survey/17.0.3.6/post-migration.py
  openupgrade_scripts/scripts/survey/17.0.3.6/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#3956 [16.0][OU-ADD] project_sms: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/project_sms/16.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#3944 [16.0][OA-ADD] project_mrp: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/project_mrp/16.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#3943 [16.0][OU-ADD] project_hr_expense: Nothing to do
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/project_hr_expense/16.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4822 [16.0][MIG] project_timesheet_holidays
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/project_timesheet_holidays/16.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4823 [16.0][MIG] purchase_product_matrix
  docsource/modules150-160.rst
  openupgrade_scripts/scripts/purchase_product_matrix/16.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4290 [MIG] l10n_it_account_balance_eu: Rename to l10n_it_financial_statement_eu
  openupgrade_scripts/apriori.py
Labels: approved

#4645 [17.0][OU-ADD] website_mail: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4688 [17.0][OU-ADD] website_partner: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_partner/17.0.0.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4605 [17.0][OU-ADD] website_sms: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4147 Renamed assets_management to l10n_it_asset_management
  openupgrade_scripts/apriori.py
Labels: approved

#4797 [17.0][OU-ADD] website_blog: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_blog/17.0.1.1/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4799 [17.0][OU-ADD] website_mass_mailing: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_mass_mailing/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4825 [17.0][OU-FIX] website: avoid website_meta_description changes
  openupgrade_scripts/scripts/website/17.0.1.0/noupdate_changes.xml
  openupgrade_scripts/scripts/website/17.0.1.0/post-migration.py
Labels: bot is merging ⏳

#4676 [17.0][OU-ADD] website_event: Migration scripts
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_event/17.0.1.4/post-migration.py
  openupgrade_scripts/scripts/website_event/17.0.1.4/pre-migration.py
  openupgrade_scripts/scripts/website_event/17.0.1.4/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4826 [17.0][MIG] hr_expense
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_expense/17.0.2.0/post-migration.py
  openupgrade_scripts/scripts/hr_expense/17.0.2.0/pre-migration.py
  openupgrade_scripts/scripts/hr_expense/17.0.2.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4604 [17.0][OU-ADD] website_crm_sms: Nothing to do
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Dependency OK

#4833 [17.0][MIG] website_profile
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_profile/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/website_profile/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4834 [17.0][MIG] website_google_map
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4838 [17.0][MIG] website_slides
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_slides/17.0.2.7/post-migration.py
  openupgrade_scripts/scripts/website_slides/17.0.2.7/pre-migration.py
  openupgrade_scripts/scripts/website_slides/17.0.2.7/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4840 [15.0][OU-FIX] mail: channel_all_employees doesn't need to be modified
  openupgrade_scripts/scripts/mail/15.0.1.5/noupdate_changes.xml
Labels: approved

#4693 [17.0][OU-ADD] hr_attendance_geolocation: Merged into hr_attendance
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/hr_attendance/17.0.2.0/pre-migration.py
Labels: Blocked by dependency

#4795 [17.0][OU-ADD] l10n_es: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/l10n_es/17.0.5.4/pre-migration.py
  openupgrade_scripts/scripts/l10n_es/17.0.5.4/upgrade_analysis_work.txt
Labels: Dependency OK

#4835 [17.0][MIG] membership
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/membership/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/membership/17.0.1.0/upgrade_analysis_work.txt
Labels: needs review, approved, Dependency OK

#4848 [17.0][MIG] privacy_lookup
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/privacy_lookup/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4849 [17.0][MIG] base_install_request
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/base_install_request/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4850 [17.0][MIG] auth_totp_mail
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/auth_totp_mail/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4851 [17.0][MIG] account_payment_term
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/account/17.0.1.2/post-migration.py
  openupgrade_scripts/scripts/account_payment_term/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4853 [17.0][MIG] sale_async_emails
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_async_emails/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4854 [17.0][MIG] purchase_mrp
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/purchase_mrp/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4857 [17.0][MIG] spreadsheet_dashboard
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/spreadsheet_dashboard/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/spreadsheet_dashboard/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4858 [17.0][MIG] spreadsheet_account & spreadsheet_dashboard_account
  docsource/modules160-170.rst
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4859 [17.0][OU-ADD] google_calendar: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/google_calendar/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4862 [17.0][MIG] sale_expense
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_expense/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4864 [17.0][MIG] spreadsheet_dashboard_(sale,purchase,stock,expense)
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4863 [17.0][OU-ADD] hr_gamification: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_gamification/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4865 [17.0][OU-ADD] website_links: Nothing to do
  docsource/modules160-170.rst
Labels: Nothing to do, Dependency OK

#4866 [17.0][OU-ADD] hr_holidays_attendance: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/hr_holidays_attendance/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/hr_holidays_attendance/17.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4876 [18.0][MIG] uom
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/uom/18.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Nothing to do, Dependency OK

#4744 [18.0][OU-ADD] web_tour
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/web_tour/18.0.1.0/end-migration.py
  openupgrade_scripts/scripts/web_tour/18.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/web_tour/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4861 [17.0][OU-ADD] mass_mailing_crm: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/mass_mailing_crm/17.0.1.0/upgrade_analysis_work.txt
Labels: Blocked by dependency, Nothing to do

#4860 [17.0][OU-ADD] mass_mailing_sale: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/mass_mailing_sale/17.0.1.0/upgrade_analysis_work.txt
Labels: Blocked by dependency, Nothing to do

#4704 [17.0][OU-ADD] sale_project: Migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/sale_project/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/sale_project/17.0.1.0/upgrade_analysis_work.txt
Labels: approved, Blocked by dependency, ready to merge

#4775 [17.0][OU-ADD] website_sale_stock: nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_sale_stock/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳, Dependency OK

#4630 [17.0][OU-ADD] website_sale_wishlist: Nothing to do
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/website_sale_wishlist/17.0.1.0/upgrade_analysis_work.txt
Labels: Nothing to do, Dependency OK

#4743 [18.0][OU-ADD] html_editor: nothing to do
  docsource/modules170-180.rst
  openupgrade_scripts/scripts/html_editor/18.0.1.0/upgrade_analysis_work.txt
Labels: Dependency OK

#4489 [17.0][OU-ADD] point_of_sale: migration to 17.0
  docsource/modules160-170.rst
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/noupdate_changes.xml
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/post-migration.py
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/pre-migration.py
  openupgrade_scripts/scripts/point_of_sale/17.0.1.0.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4879 [17.0][MIG] website_sale_digital (merged into website_sale)
  docsource/modules160-170.rst
  openupgrade_scripts/apriori.py
  openupgrade_scripts/scripts/sale/17.0.1.2/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/website_sale/17.0.1.1/post-migration.py
  openupgrade_scripts/scripts/website_sale/17.0.1.1/upgrade_analysis.txt
  openupgrade_scripts/scripts/website_sale/17.0.1.1/upgrade_analysis_work.txt
Labels: Dependency OK

#4867 [17.0][IMP] new analysis (20th March 2025)
  openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/base/17.0.1.3/upgrade_general_log.txt
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis.txt
  openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
  openupgrade_scripts/scripts/l10n_ar/17.0.3.6/upgrade_analysis.txt
  openupgrade_scripts/scripts/l10n_es/17.0.5.4/upgrade_analysis.txt
  openupgrade_scripts/scripts/purchase/17.0.1.2/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_pdf_quote_builder/17.0.1.0/upgrade_analysis.txt
  openupgrade_scripts/scripts/sale_timesheet/17.0.1.0/upgrade_analysis.txt
Labels: needs review

#4885 [17.0][OU-IMP] delivery: Finish migration scripts
  openupgrade_scripts/scripts/delivery/17.0.1.0/post-migration.py
  openupgrade_scripts/scripts/delivery/17.0.1.0/pre-migration.py
  openupgrade_scripts/scripts/delivery/17.0.1.0/upgrade_analysis_work.txt
Labels: bot is merging ⏳

#4893 [16.0][OU-ADD] l10n_es: Add migration stcripts for the merge of IRNR taxes to Spanish localization
  openupgrade_scripts/scripts/l10n_es/16.0.5.3/post-migration.py
Labels: approved

#4901 [17.0][IMP] pin random github actions to their SHA commit
  .github/workflows/documentation-commit.yml
  .github/workflows/test.yml
Labels: approved

#4899 [15.0][OU][FIX] point_of_sale: empty journal in bank payment method
  openupgrade_scripts/scripts/point_of_sale/15.0.1.0.1/post-migration.py
Labels: approved, Dependency OK

#4905 [17.0][OU-ADD] project_purchase: Nothing to do
  docsource/modules160-170.rst
Labels: Dependency OK
